### ISSUE TITLE
Proven to run local

### ISSUE THREAD

**Issue by Nbtguyoriginal** [OpenBMB/ChatDev#102]
Add a section to the installation read me to highlight this as an option 

https://github.com/OpenBMB/ChatDev/issues/27#issuecomment-1735911721

Running locally with different models may provide inconsistent results for users... but this open the door to taining a chatdev specific llm model 😀

Wich imo should highly be considered 🤔

**Comment by Alphamasterliu** [comment]
Thank you very much for your suggestions. We will consider sharing these two meaningful guides with everyone: https://github.com/OpenBMB/ChatDev/issues/27#issuecomment-1735911721; https://github.com/OpenBMB/ChatDev/pull/53

**Comment by Alphamasterliu** [comment]
Feel free to share any ideas you have at any time, and please look forward to our updates. We greatly appreciate your support and attention to our ChatDev.
