### ISSUE TITLE
Issue when creating an app

### ISSUE THREAD

**Issue by Jett21** [OpenBMB/ChatDev#105]
HI after following the instruction and installing it on windows, I've got this error:

Note that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word <INFO>, followed by our final product modality without any other words, e.g., "<INFO> PowerPoint".

Traceback (most recent call last):
  File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\ChatDev\camel\utils.py", line 147, in wrapper
    raise ValueError('OpenAI API key not found.')
ValueError: OpenAI API key not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ChatDev\run.py", line 111, in <module>
    chat_chain.execute_chain()
  File "C:\ChatDev\chatdev\chat_chain.py", line 160, in execute_chain
    self.execute_step(phase_item)
  File "C:\ChatDev\chatdev\chat_chain.py", line 130, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\ChatDev\chatdev\phase.py", line 292, in execute
    self.chatting(chat_env=chat_env,
  File "C:\ChatDev\chatdev\utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "C:\ChatDev\chatdev\phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\ChatDev\camel\agents\role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x22aeb03b670 state=finished raised ValueError>]

**Comment by hunter129143** [comment]
It seems that you have an API error or used a 3.5 API, which caused the problem. Please provide reference only

**Comment by 1iceberg1** [comment]
I have the same problem.
Can you tell me which API key I should use?
Thanks.

**Comment by hunter129143** [comment]
你好。已收到你的邮件，我会尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by hunter129143** [comment]
I think that the gpt-4 API is what you should try

**Comment by hunter129143** [comment]
or  Add @Retry(wait=wait_exponential(min=1, max=60)) above the OpenAIModel class and my problem is solved (using 3.5 turbo).

**Comment by RoniSaroniemi** [comment]
If you are using Google Colab, it is likely a syntax error. Correct way to define api key is:
%env OPENAI_API_KEY=[your key here

Note that there is no " " or ' ' surrounding the key. 

Hope this helps ;)

**Comment by lafintiger** [comment]
When I get a key from https://platform.openai.com/account/api-keys, I dont see an option for gpt 3 or 4. I assume it is just 4.

I am on a mac and tried to export the key and did not work. Can we just hard code it somewhere?

**Comment by alam234** [comment]
> or Add @Retry(wait=wait_exponential(min=1, max=60)) above the OpenAIModel class and my problem is solved (using 3.5 turbo).

Is 

> HI after following the instruction and installing it on windows, I've got this error:
> 
> Note that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word , followed by our final product modality without any other words, e.g., " PowerPoint".
> 
> Traceback (most recent call last): File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity__init__.py", line 382, in **call** result = fn(*args, **kwargs) File "C:\ChatDev\camel\utils.py", line 147, in wrapper raise ValueError('OpenAI API key not found.') ValueError: OpenAI API key not found.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\ChatDev\run.py", line 111, in chat_chain.execute_chain() File "C:\ChatDev\chatdev\chat_chain.py", line 160, in execute_chain self.execute_step(phase_item) File "C:\ChatDev\chatdev\chat_chain.py", line 130, in execute_step self.chat_env = self.phases[phase].execute(self.chat_env, File "C:\ChatDev\chatdev\phase.py", line 292, in execute self.chatting(chat_env=chat_env, File "C:\ChatDev\chatdev\utils.py", line 77, in wrapper return func(*args, **kwargs) File "C:\ChatDev\chatdev\phase.py", line 131, in chatting assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1) File "C:\ChatDev\camel\agents\role_playing.py", line 242, in step assistant_response = self.assistant_agent.step(user_msg_rst) File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity__init__.py", line 289, in wrapped_f return self(f, *args, **kw) File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity__init__.py", line 379, in **call** do = self.iter(retry_state=retry_state) File "C:\Users\Jett\anaconda3\envs\chatdev_conda_env\lib\site-packages\tenacity__init__.py", line 326, in iter raise retry_exc from fut.exception() tenacity.RetryError: RetryError[<Future at 0x22aeb03b670 state=finished raised ValueError>]

I got the same error. But what works for me was, in the utils.py, instead of this :

import os
import re
import zipfile
from functools import wraps
from typing import Any, Callable, List, Optional, Set, TypeVar

I add one more line where I force the code to search in the environment variables: 

import os
import re
import zipfile

openai_api_key = os.environ['OPENAI_API_KEY']
from functools import wraps
from typing import Any, Callable, List, Optional, Set, TypeVar

This works for me!!

**Comment by Korner83** [comment]
Same issue here on Win10, but non of the above solutions helped me. (api key is properly set as an env. variable)

**Comment by Korner83** [comment]
set OPENAI_API_KEY=<yourkey>
after that echo %OPENAI_API_KEY% to check if it is still not working you can try setx OPENAI_API_KEY “<yourkey>”

**Comment by 1iceberg1** [comment]
I solved the problem.
In my case, it occurs because of setting environment value(OPENAI_API_KEY 4.0).
I set it manually from windows settings and restarted my computer.
And the problem dealt.

**Comment by Solobearus** [comment]
how to manually set it from windows settings?

**Comment by 1iceberg1** [comment]
> how to manually set it from windows settings? 

My Computer ->System Properties -> Advanced ->Environment Variables -> New
Set the Variable name and Variable value

**Comment by Mr-Babarkhan** [comment]
> If you are using Google Colab, it is likely a syntax error. Correct way to define api key is: %env OPENAI_API_KEY=[your key here]
> 
> Note that there is no " " or ' ' surrounding the key.
> 
> Hope this helps ;)

it solved my issue
