### ISSUE TITLE
Error while doing replay

### ISSUE THREAD

**Issue by talhadar90** [OpenBMB/ChatDev#107]
Heres the console log on chrome

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'imgid')
    at updateCompanyWorking (app.js:519:37)
    at createPara (app.js:395:9)
    at replayDialog (app.js:187:15)
updateCompanyWorking @ app.js:519
createPara @ app.js:395
replayDialog @ app.js:187
await in replayDialog (async)
(anonymous) @ app.js:111

Please help

**Comment by thinkwee** [comment]
Thank you for your report, we will look into it. Could you please share the log that you replayed?

**Comment by NA-Wen** [comment]
Some early version of logs is not supported, try to choose logs with later timestamp from the Warehouse. And the detailed log you used is preferred for better solving your problem.
