### ISSUE TITLE
Setup instructions on Windows - README.md

### ISSUE THREAD

**Issue by yraen69** [OpenBMB/ChatDev#112]
Assumes you have Conda installed and know what it is.

Might be worth expanding that section of the how to landing page to include some links for Windows users:

Maybe link to the Mini Conda installer:
https://docs.conda.io/projects/miniconda/en/latest/

Then be clear that just typing 'conda' into a terminal on Windows will do nothing except throw an error, you have to specify the install path first so these commands don't work:

conda create -n ChatDev_conda_env python=3.9 -y
conda activate ChatDev_conda_env

the need to be more like

C:\Users\ *****\miniconda3\condabin\conda create -n ChatDev_conda_env python=3.10 -y

C:\Users\ *****\miniconda3\condabin\conda activate ChatDev_conda_env

Also note worth moving to recommending Python 3.10 as it's a security release to fix CVE's in 3.9. Using 3.9 is not recommended anymore and all users should have long since upgraded.

**Comment by BozhokAnastasia** [comment]
I also had problems with the setup instructions for Linux. Specifically, using Python version 3.9 does not work with Ubuntu, but Python 3.10 does.

So instead of
`conda create -n ChatDev_conda_env python=3.9 -y`

the doc should say
`conda create -n ChatDev_conda_env python=3.10 -y`

**Comment by Alphamasterliu** [comment]
Thank you very much for your supplementary suggestions on the details. We will fully consider incorporating this idea in the next update of the README. Please look forward to it.
