### ISSUE TITLE
No module named 'openai'

### ISSUE THREAD

**Issue by thatdudeagain** [OpenBMB/ChatDev#113]
when i run 
python run.py --task "[description_of_your_idea]" --name "[project_name]"

returns  ModuleNotFoundError: No module named 'openai'

in

  File "C:\Users\Dev\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "C:\Users\Dev\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "C:\Users\Dev\ChatDev\camel\agents\__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "C:\Users\Dev\ChatDev\camel\agents\chat_agent.py", line 24, in <module>
    from camel.model_backend import ModelBackend, ModelFactory
  File "C:\Users\Dev\ChatDev\camel\model_backend.py", line 17, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by konakoffee** [comment]
Did you find a solution I also have this problem.

**Comment by pratikkuikel** [comment]
@thatdudeagain I am facing the same problem, How did you reslove this problem ?

**Comment by rwilkin** [comment]
I fixed the problem by renaming the `ChatDev` folder (in the same folder as run.py) to `chatdev` - it is case sensitive. If you are in Windows you will need to rename it to something like `ChatDev2` then rename it again to `chatdev`. Windows isn't case sensitive so if you try to rename `ChatDev` to `chatdev` it'll revert it back to `ChatDev`
