### ISSUE TITLE
Feature request: interactive participation in design stage

### ISSUE THREAD

**Issue by steamorchid** [OpenBMB/ChatDev#115]
It would be great to have the user participate in the iterative process of gathering and specifying requirements.

**Comment by yraen69** [comment]
You can already, there is a human step you can insert into the phases, you can then provide either a new feature or a bug report.

**Comment by delconis** [comment]
The project contain's an example use option `--config Human` and inspect the `CompanyConfig/Human` 

This is what I think you are looking for
```
{
      "phase": "HumanAgentInteraction",
      "phaseType": "ComposedPhase",
      "cycleNum": 5,
      "Composition": [
        {
          "phase": "CodeReviewHuman",
          "phaseType": "SimplePhase",
          "max_turn_step": 1,
          "need_reflect": "False"
        }
      ]
    },
```

**Comment by delconis** [comment]
But this issue should be closed or re-wrote to be Update the wiki.md to include instructions on how to use the HumanAgentInteractions in your ChatChains
