### ISSUE TITLE
pycache removed why?

### ISSUE THREAD

**Issue by GeneralHangman** [OpenBMB/ChatDev#126]
a the end of generating its allways comming at end cd: ... __pycache__ Removed

**Comment by Alphamasterliu** [comment]
Hello, the removal of the pycache is a feature we designed in ChatChain to delete unnecessary cache. If you'd like to keep it, you can go to the ChatChainConfig.json file in the CompanyConfig/Default folder and locate the line 96, which reads "clear_structure." Change "True" to "False" to retain the pycache.

**Comment by Alphamasterliu** [comment]
![image](https://github.com/OpenBMB/ChatDev/assets/110011045/c7588ab3-970d-4354-b3ed-d383f936900f)
