### ISSUE TITLE
 Incorrect API key provided:

### ISSUE THREAD

**Issue by Devchandrasen** [OpenBMB/ChatDev#128]
Even after inputting the correct API key it still shows that the Incorrect API key provided: "sk-RoCv*****************************************ABM". You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by YanWittmann** [comment]
Having the same issue here. Tested the key manually, does not work. Even after removing it and creating a new one, the issue persists.

**Comment by nanukmx** [comment]
Same issue here :( I tried the key on another program and it is working

**Comment by Vermino** [comment]
> Even after inputting the correct API key it still shows that the Incorrect API key provided: "sk-RoCv*****************************************ABM". You can find your API key at https://platform.openai.com/account/api-keys.

If you are running it on Windows (Anaconda Prompt), Try:
set OPENAI_API_KEY=sk-Rja****************************************HaM

Of course, replacing the API KEY with yours.

**Comment by Kiwiboys-alt** [comment]
> > Even after inputting the correct API key it still shows that the Incorrect API key provided: "sk-RoCv*****************************************ABM". You can find your API key at https://platform.openai.com/account/api-keys.
> 
> If you are running it on Windows (Anaconda Prompt), Try: `set OPENAI_API_KEY=sk-Rja****************************************HaM`
> 
> Of course, replacing the API KEY with yours.

I am using Windows and did try this, but it still did not work the error message confirms that the key it is trying to use is correct but it seems like it's just not being accepted, I;ve tried several different keys all newly generated still no results. Could it be Open AI blocking this?

**Comment by Kiwiboys-alt** [comment]
> > Even after inputting the correct API key it still shows that the Incorrect API key provided: "sk-RoCv*****************************************ABM". You can find your API key at https://platform.openai.com/account/api-keys.
> 
> If you are running it on Windows (Anaconda Prompt), Try: `set OPENAI_API_KEY=sk-Rja****************************************HaM`
> 
> Of course, replacing the API KEY with yours.

Yes, using set worked, But you **also need to remove the quotes!** A small gotcha that had me for a bit there.

**Comment by Devchandrasen** [comment]
Thanks That Works for me .
