### ISSUE TITLE
Is this a static or active repo?

### ISSUE THREAD

**Issue by matecsaj** [OpenBMB/ChatDev#133]
Is this repository:

1. An unchanging resource intended for readers of the [paper](https://arxiv.org/pdf/2307.07924.pdf)?

2. Or the start of an active project? Will there be regular releases, and do you welcome issues and pull requests?

**Comment by Alphamasterliu** [comment]
Thank you for your interest in ChatDev. We are an active open-source repository and always pay close attention to everyone's issues and pull requests, maintaining a continuous process of updates, which is something we highly value. So, if you have any questions, suggestions, or ideas for contributions, please feel free to reach out at any time.😊

**Comment by matecsaj** [comment]
Glad to hear it, thanks! To make this obvious, please consider adding a roadmap and contributor guide.

**Comment by Alphamasterliu** [comment]
🆗 We will take everyone's feedback into careful consideration and make targeted updates to the README guide. Please stay tuned for these improvements.
