### ISSUE TITLE
Set different models for different AImployees

### ISSUE THREAD

**Issue by Elliot-Construct** [OpenBMB/ChatDev#134]
I think it would be great to be able to give the CTO GPT4 access, with a coding team that has 3.5-turbo.

Things of that nature.

Plus an ability to pick up projects that have already been started and use the documentation team to analyse what it does and what stage it is at, then pass it onto the relevant teams to continue the project.

**Comment by Alphamasterliu** [comment]
Thank you for your support and suggestions for our ChatDev. We have been considering this idea, but it has not been developed at the moment. However, considering the significant user demand and practical value, this will be one of our major feature goals in the future. We appreciate your ongoing interest, and please stay tuned for updates.
