### ISSUE TITLE
Where did you get your CAMEL code?

### ISSUE THREAD

**Issue by OctagonalHexy** [OpenBMB/ChatDev#135]
I was poking around the repo looking for hints about how the agents are being chained together and noticed CAMEL, so I looked it up.

It seems to be A specification for chaining AI models and other software utility's for them, but I cant find the repo I assume the CAMEL implementation came from given its license credits CAMEL-AI.org  ( turns out their url is camelai.org).

Then again, given how specific to this project some of that code is I imagine that maybe someone from camelai may have contributed it for this project specifically and just happened to use A specification they were already working on. ( pure speculation on my part ) 

Anyway, I'm just curious about CAMEL. Is it just super new and has no reference implementations?

**Comment by Alphamasterliu** [comment]
Hello, we've used Camel's framework ( https://github.com/camel-ai) for a portion of our project, as it indeed offers a good approach to implementing Communicative Agents. Thank you very much for using ChatDev and your diligent attention to its artificial intelligence technologies.
