### ISSUE TITLE
Git management

### ISSUE THREAD

**Issue by djbritt** [OpenBMB/ChatDev#136]
Can you please provide more information in your readme.md file about git_management

Does this
1. Allow ChatDev to reopen a project after the first run?
2. How do we tell ChatDev don't make a new app, use the app you previously stored in github?

Great project otherwise, thank you guys.

**Comment by Alphamasterliu** [comment]
Hello, if you want to open the pre-existing software we've uploaded to the GitHub Warehouse, simply enter "python main.py (the corresponding file's path)" in your terminal. However, if you're looking to continue or modify existing code or work on partially completed projects using ChatDev, we currently do not support that functionality. 
Nevertheless, given the significant user demand and its practical value, this is one of our future goals. We will take everyone's feedback into careful consideration and make targeted updates to the README guide. Please stay tuned. Thank you for your support and efforts with our ChatDev project. 😊

**Comment by djbritt** [comment]
Sorry, I also would like more information about what git_management actually does, I don't think your readme or wiki explains it very well. Would you be willing to expand on this?

September 25th, 2023: The Git feature is now available, enabling the programmer  to utilize GitHub for version control. To enable this feature, simply set "git_management" to "True" in ChatChainConfig.json.

**Comment by thinkwee** [comment]
Sorry for the confusion. We will update the wiki and explain the git function.

**Comment by thinkwee** [comment]
We have updated the wiki, you can see introduction at https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#git-mode
