### ISSUE TITLE
Create new project for examples

### ISSUE THREAD

**Issue by delconis** [OpenBMB/ChatDev#141]
I strongly feel the warehouse directory have all examples excluded and ignored in `.gitignore. `

They are not contributing value to the application runtime and after execution creates an excess of un-staged files to commit on Git.

1 or 2 examples would be acceptable for the provided ChatChains in my mine, but I do feel the warehouse directory should be added to the .gitignore

**Comment by ManindraDeMel** [comment]
I think the maintainers would like the community to contribute to the different projects they've accomplished. It might be more valuable to create a dedicated website or discord channel (like OpenAI's discord) showcasing all the different projects that have been achieved using ChatDev

**Comment by thinkwee** [comment]
Yes, we have noticed the problem and may build an independent website (or in other forms) for online demos and community-contributed software.

**Comment by ManindraDeMel** [comment]
> Yes, we have noticed the problem and may build an independent website (or in other forms) for online demos and community-contributed software.

Let me know if you need any help building such a website! (or other form of platform for online demos)

**Comment by thinkwee** [comment]
now we have a SaaS platform, https://chatdev.modelbest.cn/
