### ISSUE TITLE
Human feedback phase should allow multi-line feedback and should flush stdin just beforehand

### ISSUE THREAD

**Issue by mowliv** [OpenBMB/ChatDev#145]
I tried giving human feedback and had these problems:

1. I needed to give multi-line feedback. I wanted to add a feature and also I wanted to paste in an exception that I was getting. The problem is everything entered needs to be on one line. I should be able to give feedback up until an EOF marker, or a line with some demarcation like END alone on a line.

2. Input should be flushed before it asks for a round of human feedback. Because of the above issue, every time it went to ask for human feedback, it already had several lines of the exception pending in STDIN, and so each time it would just take one of those lines that had been entered way beforehand. It would be good to flush STDIN just before asking for feedback.

**Comment by ynvtlmr** [comment]
How about adding the ability to feed a design document file as input for the "task" instead of a one-liner inputted in the command prompt? This could allow people to define a better fleshed out idea with more detailed specifications.

**Comment by mowliv** [comment]
That would be great.

**Comment by Alphamasterliu** [comment]
Hello! Thank you very much for this valuable suggestion. We will strive to optimize the Human-Agent-Interaction mode within this week. Your patience is much appreciated.

**Comment by mowliv** [comment]
excellent!
