### ISSUE TITLE
After running, it is leaving Mac terminal window with light gray text color

### ISSUE THREAD

**Issue by mowliv** [OpenBMB/ChatDev#146]
Bug: after I run run.py, it is leaving my mac terminal window with light gray text. I need to run "reset" to fix it. Before I ran reset, my command prompt, and all following commands, would show in that same light gray.

<img width="1246" alt="image" src="https://github.com/OpenBMB/ChatDev/assets/4602829/6c3a5e51-f3cb-4a4c-9cac-410693a5884f">

**Comment by mowliv** [comment]
Here is where it all went light gray in my last run:

<img width="1247" alt="image" src="https://github.com/OpenBMB/ChatDev/assets/4602829/c219d18b-0ae9-4405-804a-9d6825c56a8f">

**Comment by Alphamasterliu** [comment]
Hello, thank you very much for trying out ChatDev. I'd like to ask if the grayed-out font situation affects the program's functionality? Is there an error message, or is it just the font appearing grayed out?

**Comment by mowliv** [comment]
Just turns the terminal text gray and leaves it gray after the program
ends.

**Comment by thinkwee** [comment]
It is a strange phenomenon, I don't have this problem on the Mac terminal. Pull the latest code and try again?
