### ISSUE TITLE
Is there a way to request agents to improve on an existing code base instead of creating new software?

### ISSUE THREAD

**Issue by mio-19** [OpenBMB/ChatDev#147]
It would be very useful if I can ask agents to fix a bug or add a new feature on an existing project

**Comment by Alphamasterliu** [comment]
Hello! You may want to take a look at the Human-Agent Interaction feature we updated on September 20th. You can use this config to assume the role of a reviewer, and we hope this can help you achieve better idea reproduction. If you're looking to continue or modify existing code or work on partially completed projects using ChatDev, we currently do not support that functionality. Nevertheless, given the significant user demand and its practical value, this is one of our future goals. Please stay tuned. Thank you for your support and efforts with our ChatDev project. 😊

**Comment by drunkducker** [comment]
I feel #151 would also tie into this request, with he sentence "given the significant user demand and its practical value, this is one of our future goals". I would like to add to that user demand.

**Comment by delconis** [comment]
Related Issues: #94 #157 #80
