### ISSUE TITLE
Security Issue: Dangerous Process Call

### ISSUE THREAD

**Issue by sectheops** [OpenBMB/ChatDev#153]
subprocess-shell-true

Found subprocess function $FUNC with shell=True. This is dangerous because this call will spawn the command using a shell process. Doing so propagates current shell settings and variables, which makes it much easier for a malicious actor to execute commands. Use shell=False instead.

Vulnerabilities and their line numbers:
chatdev/chat_chain.py:256
chatdev/chat_env.py:59
chatdev/chat_env.py:90
chatdev/chat_env.py:99
chatdev/codes.py:102

***Reccomendation***
Avoid using shell=True when making commands dynamically, it introduces security risks. I recommend using subprocess.run to pass commands and arguments separately.

Attached is an example fix for chatdev/chat_env.py:59

[import subprocess.zip](https://github.com/OpenBMB/ChatDev/files/12847007/import.subprocess.zip)

**Comment by thinkwee** [comment]
Thank you and we would consider docker support. #203
