### ISSUE TITLE
no URL configured for submodule "WareHouse/ChatDev"

### ISSUE THREAD

**Issue by PhDave13** [OpenBMB/ChatDev#154]
When cloning main branch from URL https://github.com/OpenBMB/ChatDev.git, I get a message which reads

"no URL configured for submodule "WareHouse/ChatDev"

Running Windows 11.

Configuration bug?

<img width="1583" alt="Screenshot 2023-10-09 175922" src="https://github.com/OpenBMB/ChatDev/assets/39740343/99ae2024-5b93-42ee-b4f7-169ecca0ee3a">

**Comment by thinkwee** [comment]
It seems like someone introduced some wrong folders in the software contribution. I have cleaned it. Please try again
