### ISSUE TITLE
Security Issue: DOM-Based Vulnerabilities.

### ISSUE THREAD

**Issue by sectheops** [OpenBMB/ChatDev#158]
Non-sanitized usage of insecure document methods.

We found some vulnerabilities in the app.js file where user controlled data in methods like innerHTML, outerHTML or document.write is used that can lead to XSS vulnerabilities. The vulnerability was enumerated as "CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')".

Line numbers for the vulnerabilities found:
online_log/static/replay/js/app.js:184
online_log/static/replay/js/app.js:205
online_log/static/replay/js/app.js:412
online_log/static/replay/js/app.js:479
online_log/static/replay/js/app.js:487
online_log/static/replay/js/app.js:492
online_log/static/replay/js/app.js:496
online_log/static/replay/js/app.js:504
online_log/static/replay/js/app.js:545

***Recommendation:***
Sanitization of the input through designated libraries such as "DOMPurify" to the vulnerable methods, such as the filename variable being passed to innerhtml on line 184 and 205. Alternatively, please consider using methods like "textContent" or other DOM manipulation techniques and avoid inputting html unless extremely necessary to ensure that user-generated content is treated as plain text and the likelihood of an XSS attack being implemented is reduced.

**Comment by NA-Wen** [comment]
Thank you for your suggestions. Now the `replay.html` is a static web page, and the attack surface of XSS vulnerabilities on local static web pages is quite small. We will take it into consideration in further development.
