### ISSUE TITLE
MAKE DARK MODE

### ISSUE THREAD

**Issue by GuyARoss** [OpenBMB/ChatDev#160]
IT IS 12AM, I OPEN UI IN DARK ROOM, EYES HURT!

Edit: I noticed that the replay UI is dark mode. BUG, PLZ FIX

**Comment by Alphamasterliu** [comment]
Could you provide a screenshot of the BUG you mentioned?

**Comment by 2021eo3ar** [comment]
Can you please assign me this issue, I can make a good dark mode  on website?
Can you please brief me this issue in detail?
