### ISSUE TITLE
Security Issue: Use of a possibly insecure function.

### ISSUE THREAD

**Issue by sectheops** [OpenBMB/ChatDev#162]
Usage of eval() taking (unsanitized) user input that could lead to a potential code injection in the file: /src/WareHouse/Calculator_THUNLP_20230628184918/calculator.py:36

***Recommendation:***
Avoid using eval() in such a situation if possible. Instead, we would recommend consider using safer alternatives like "ast.literal_eval" or a parser library to evaluate mathematical expressions.

**Comment by thinkwee** [comment]
It is not a part of ChatDev code but generated from ChatGPT. The code security problem from LLM is a known issue. Right now we would consider it as a preprocess (clean code corpus when pretraining LLM) or a postprocess (check the generated software with some security span tools and rewrite it) and would not modify the current ChatChain process to solve it.
