### ISSUE TITLE
ChatDev always freezes

### ISSUE THREAD

**Issue by dnhkng** [OpenBMB/ChatDev#167]
Fresh installs on Linux (Ubuntu 22) or Mac seem to freeze.

When I follow the instructions and add my API key, and use this command:

`python3 run.py --task "Create a simple pong game in python" --name "MyCalculator"
`

I get a lot of text in the terminal, ending like this:

```
Mind Map: can represent ideas, with related concepts arranged around a core concept.

As the Chief Product Officer, to satisfy the new user's demand and the product should be realizable, you should keep discussing with me to decide which product modality do we want the product to be?

Note that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word <INFO>, followed by our final product modality without any other words, e.g., "<INFO> PowerPoint".
```
At this point, nothing further happens. 
Once I got a response from OpenAI, and I saw that about 500 tokens were processed, but then the code froze again.

Is there a logging system to help debug this?

**Comment by JLPiper** [comment]
Same issue here. My install previously worked fine, now freezes at this same section.

**Comment by dneprovets** [comment]
The same behavior on mac

**Comment by dneprovets** [comment]
[2023-12-10 14:56:57 INFO] error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False

Find only in logs

**Comment by Alphamasterliu** [comment]
Hello, when the conversation stops after the first turn, it could be a direct reflection of your API key not being utilized. Please check if your account has a sufficient balance (a few cents should be enough for GPT-3.5, but GPT-4 might require more), and ensure that you have configured the key's environment successfully. Your understanding is greatly appreciated. Thank you for your support and for trying out ChatDev. We remain committed to continuously enhancing the overall functionality and stability.

**Comment by markolia** [comment]
it is not true i have plenty of usage left and still get that message. its a shame always after i finally give a task it freezes so i recenty trying to find my way around w different app. would be nice if devs explain this coz its just waste of time much efficient is just to play w another ai and get anything done...

**Comment by brianlowery** [comment]
Just thought I would post this here in case it helps someone else.
I was trying to track this down myself, and went into the warehouse folder, and there is a text file named project_something_DATETIME.txt.
In that file, it shows me that my API key was incorrect.
`[2023-14-10 20:12:30 INFO] error_code=invalid_api_key error_message='Incorrect API key provided:`
I went in and just created a new API key, updated it and was able to run my project successfully.

@Alphamasterliu @markolia @dnhkng 

Maybe check that folder and provide the error code and message?

**Comment by dnhkng** [comment]
@brianlowery No, I see the first request was successful, and then nothing. Deliberately setting the API key incorrectly does generate the error message you see though.

I suspect it's a rate-limit error. I am trying with Azure access, but I'm having trouble with access, and am seeking help here #191

**Comment by brianlowery** [comment]
@dnhkng so you see the successful request, and then you have nothing else in that file?

**Comment by dnhkng** [comment]
@brianlowery I think it's due to rate limiting on my OpenAI account (I'm not an admin there, so I can't make changes). I've made PR #192 that gets Azure ChatGPT access working, so now I just use that 🤷🏻
