### ISSUE TITLE
Rate limit reached for gpt-3.5-turbo

### ISSUE THREAD

**Issue by gennadiyvorgy1** [OpenBMB/ChatDev#171]
Hello, the project started to run, everything was fine.
Then it froze and stayed there for a long time:

[2023-12-10 12:33:28 WARNING] Rate limit reached for gpt-3.5-turbo-16k-0613 in organization org-5b2xUq3Mwie1Wgwh on tokens per min. Limit: 40000 / min. Please try again in 1ms. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method., retrying in 0 seconds...

But continues to work and transmits to Open AI, requests every millisecond, so stands - project file DefaultOrganization_20231012120759.log

It accumulates messages to wait before requests from Open AI, and it continues to bomb.

That's why it hangs

Can you tell me where to put pauses before requests, that it would act not so fast or lightning fast ?

Need some pauses, delays, when receiving a warning in DefaultOrganization_20231012120759.log

ChatGPT account and API are fresh and balance is available !!!!

Thank you,

Regards.

**Comment by Alphamasterliu** [comment]
Hello! Regarding the Rate limit issue, you can refer to the discussion at this link: https://github.com/OpenBMB/ChatDev/issues/26. I believe it will provide you with some helpful insights. Thank you very much for trying out and supporting ChatDev! 😊

**Comment by SuzdalenkoAlexey** [comment]
Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo in organization org-rxenTzjMkf2Po8dsexe410Mg on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. 

I was testing when everything broke down, so it looks like you have to pay? 
I didn't think they would impose to pay so soon, I just wanted to know the tool.

**Comment by OlesiaVoloshyna** [comment]
with free key, can't I overcome this rate limit errors?
