### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by imanav10** [OpenBMB/ChatDev#184]
While installation during fourth step **_Set OpenAI API Key_**. I am getting this error called `The filename, directory name, or volume label syntax is incorrect. ` . Please someone resolve this

**Comment by LeBulius** [comment]
Same

**Comment by yashpundir** [comment]
If on windows, setting the API key using the `set varname="value"` command did work for me.

**Comment by LeBulius** [comment]
I used set OPENAI_API_KEY=abc123

**Comment by ManindraDeMel** [comment]
try using powershell. Use this for powershell `$env:OPENAI_API_KEY="your_OpenAI_API_key"`

**Comment by MaelHan** [comment]
But if i use LLM Studio guys, how i change the API url by mine ?

**Comment by thinkwee** [comment]
please refer to issue #27

**Comment by Alphamasterliu** [comment]
Hello, regarding the configuration of the OpenAI API, please use if on windows:
`set OPENAI_API_KEY=[your api key] ` on cmd
`$env:OPENAI_API_KEY="[your api key]" `  on powershell
If you are considering using other models or local models, you can refer to https://github.com/OpenBMB/ChatDev/issues/27; https://github.com/OpenBMB/ChatDev/pull/53
Thank you for your support and trying out ChatDev. Feel free to ask any questions you may have 😊
