### ISSUE TITLE
Requirements.txt error --Task Not working

### ISSUE THREAD

**Issue by GITHGene** [OpenBMB/ChatDev#188]
Hi guys,

I'm a bit of a noob but have been messing with chatgpt and know a little bit of coding.

Heres are the 2 issues:

1. While executing 

pip3 install -r requirements.txt 

I have to paste the absolute path for " requirements.txt " prior to the command and receive an error ( Image attached. )
![Screen Shot 2023-10-16 at 1 56 35 AM](https://github.com/OpenBMB/ChatDev/assets/147771136/7ef57339-9b8a-43e7-9b3a-c50578f4eb6f)

2. when I type my ChatDev task  -

python3 run.py --task “develop application to operate a business. functions include tasks lists, file sharing, group chat, and inventory checklist” -- name"BizApp"

I receive the following error:

 _File "/Users/megansmacbookair/Documents/GitHub/ChatDev/camel/agents/chat_agent.py", line 17, in <module>
    from tenacity import retry

_ModuleNotFoundError: No module named 'tenacity'__
![Screen Shot 2023-10-16 at 1 58 54 AM](https://github.com/OpenBMB/ChatDev/assets/147771136/c450855e-2ddc-4e0a-8ae4-a30282bc3642)

I have tried using ChatDev on with PyCharm and Macbook Terminal / Online repo & HD Repo

Feel kinda retarted considering how easy it is, but I need some guidance 

Your assistance is appreciated!

Thanks

**Comment by GITHGene** [comment]
Thanks Wk!

Will try & let you know

**Comment by GITHGene** [comment]
also, question:

 why would that be required?

( Just for future reference )

**Comment by ManindraDeMel** [comment]
> also, question:
> 
> why would that be required?
> 
> ( Just for future reference )

It shouldn't make a difference. Just make sure you have the latest version of pip `pip3 install --upgrade pip` . Also for the distutilts error. In python3.10+ distutils has been deprecated and removed. so you might need to switch to python 3.9. 

- Try upgrading pip3
- Try switching to python3.9

**Comment by wkf16** [comment]
> Thanks Wk!
> 
> Will try & let you know

Python and Python3 may point to different interpreters, and you need to check if your conda environment is selected correctly. You should run pip within the correct environment. Perhaps your computer has many different Python installations, and your pip command may not necessarily install packages in the right location. You can use 'python --version' and 'python3 --version' to check the versions associated with the commands.

**Comment by GITHGene** [comment]
Thats is awesome!


Running 3.12


Probably why the command isn't being processed.

Going to try tomorrow


Thank you to everyone that has been assisting!
