### ISSUE TITLE
PLEASE ADD UAT (User Acceptence Test)

### ISSUE THREAD

**Issue by fakhripraya** [OpenBMB/ChatDev#193]
hi this will be short but please add UAT, like prompt another task based on the previous task result before accepting the end product

**Comment by thinkwee** [comment]
Could you please provide more details? 
Also I wonder if Human-Interaction modes can solve your problems.

**Comment by BlinkSun** [comment]
Why you don't create your own role for that ? ChatDev have this capability to be customizable (Roles, Phases, Chains) !

**Comment by bridgebrain** [comment]
For that matter, it would be lovely if we could add a human interaction step when they're discussing concept, so they can ask for clarification before executing. I'm trying to customize my own role for it and add it to the que, but it's a bit deeper than I am.

**Comment by fakhripraya** [comment]
> For that matter, it would be lovely if we could add a human interaction step when they're discussing concept, so they can ask for clarification before executing. I'm trying to customize my own role for it and add it to the que, but it's a bit deeper than I am.

exactly

**Comment by fakhripraya** [comment]
or maybe think of us user as the client, and whenever the CEO gave us the product, whether its the final product or not depends on our decision

**Comment by fakhripraya** [comment]
thanks ill go back to this later and check it
