### ISSUE TITLE
Unable to replay from online log

### ISSUE THREAD

**Issue by init27** [OpenBMB/ChatDev#2]
Hello! 

First of all, thank you very much for the amazing research work and the open source code. It's really amazing stuff and great learning! 

I wanted to file an issue:

When I try to run the `online_log/app.py`

I am able to upload the `ChaiChainConfig.json` but when I try to do a replay and upload the log file, the "File Upload" button is unresponsive. 

The logs are quite readable and so is the json file, but it would be super cool if I was able to re run the log visualiser. 

I'm on Mac OS, tested on Safari, Chrome and Firefox

Thanks in advance!

**Comment by thinkwee** [comment]
Thank you for your feedback!

1. After you run ``online_log/app.py``, there are three pages, on the main page there are two buttons linked to other two pages. Make sure you are using the right page.
    - on ``http://127.0.0.1:8000/`` you can see the real-time log information in ``run.py``; 
    - on ``http://127.0.0.1:8000/static/chain_visualizer.html`` you can upload and visualize a ``ChatChainConfig.json`` in ``CompanyConfig/Default/``
    - on ``http://127.0.0.1:8000/static/replay.html``  you can upload and visualize a log under ``WareHouse/xxx/``
2. There may be some old logs that can not be replayed, you can try any software with a timestamp in 20230825 or newer, such as ``WareHouse/DigitalClock_THUNLP_20230825093556``
3. Every time you try to upload and replay a new log, you can refresh the page. We will improve the demo in the future
 
Please let me know if it solves your problem.

**Comment by parvizdinmohammadi** [comment]
> Hello!
> 
> First of all, thank you very much for the amazing research work and the open source code. It's really amazing stuff and great learning!
> 
> I wanted to file an issue:
> 
> When I try to run the `online_log/app.py`
> 
> I am able to upload the `ChaiChainConfig.json` but when I try to do a replay and upload the log file, the "File Upload" button is unresponsive.
> 
> The logs are quite readable and so is the json file, but it would be super cool if I was able to re run the log visualiser.
> 
> I'm on Mac OS, tested on Safari, Chrome and Firefox
> 
> Thanks in advance!

Hello my friend
i looked your message and was glad.actually i,m amatur at programing but i suggest you using of chatAI for resolving problem.
if you find it forward to me for study please.
thank you indeed
