### ISSUE TITLE
Add Hindi README

### ISSUE THREAD

**Issue by Durgesh4993** [OpenBMB/ChatDev#200]
I created Hindi translated README.

**Comment by ManindraDeMel** [comment]
Did you make a PR?

**Comment by Durgesh4993** [comment]
No till now can i

**Comment by ManindraDeMel** [comment]
> Did you make a PR?

oh you did #177

**Comment by Durgesh4993** [comment]
Can i do it any other language i am also able to do in
- German
- Japnese 
- Chinese

**Comment by ManindraDeMel** [comment]
Im planning on automating the translations of readmes. See #180
