### ISSUE TITLE
Feature Request: Continue development from a pre-existing directory

### ISSUE THREAD

**Issue by MetcalfeTom** [OpenBMB/ChatDev#219]
**Summary:**
The current framework initiates a new directory every time a new task is started. Users may wish to continue development on an existing project, adding new features or making improvements upon pre-existing code. I propose a feature to specify a pre-existing directory for continued development.

I've been working on this feature locally and would be happy to contribute via a PR. I'd like to align with the maintainers on its utility and any requirements/desires for the contribution 🚀

**Proposed Approach:**
- Add a new default config with:
  - `clear_structure=False`
  - no initial`Coding` step phase in the chain
- Implement a flag or command-line argument `--continue-from-dir=[Path_to_directory]` which loads the above config
- Use the path to run `chat_env._load_from_hardware()` during `pre_processing`

**Comment by wyifei26** [comment]
Thank you for your suggestions and ideas! We update the incremental development mode today, let's see if it meets your needs!
