### ISSUE TITLE
Chat Replay 'File Upload' button not working

### ISSUE THREAD

**Issue by vinaypateel** [OpenBMB/ChatDev#227]
After finishing a demo app development, I tried to check out the Chat Replay functionality.

I was given the URL "http://127.0.0.1:8000/"
I chose 'Chat Reply'
When I clicked on 'File Upload' button, nothing happens.

But the file upload functionality inside 'ChatChain Visualizer' seems to work.

**Comment by NA-Wen** [comment]
Please refer to #58. Hope this will help solve your problem.
