### ISSUE TITLE
Chatdev gets stuck

### ISSUE THREAD

**Issue by irtiq7** [OpenBMB/ChatDev#229]
I ran a task that got stuck  at this point:

💰**cost**=$0.065786

🔨**version_updates**=-1

📃**num_code_files**=2

🏞**num_png_files**=0

📚**num_doc_files**=4

📃**code_lines**=41

📋**env_lines**=-1

📒**manual_lines**=-1

🗣**num_utterances**=28

🤔**num_self_reflections**=0

❓**num_prompt_tokens**=10922

❗**num_completion_tokens**=8255

🌟**num_total_tokens**=19177

**[Execute Detail]**

execute SimplePhase:[TestErrorSummary] in ComposedPhase:[Test], cycle 1

Could you suggest what could be the issue?

**Comment by Ressnn** [comment]
Can you describe the steps you took which created the issue? What configs did you use, what prompt, etc. Does it seem to consistently get stuck at this point, or is it sporadic?

**Comment by irtiq7** [comment]
I think I figured it out. I tried reinstalling the packages from requirement.txt and everything seems to be okay
