### ISSUE TITLE
Adding new employees to the company

### ISSUE THREAD

**Issue by irtiq7** [OpenBMB/ChatDev#231]
Hi there,

If I want to add a new employee to the software house, what are the processes involved? And what files should I update to reflect that? I couldn't seem to find the info on the paper.

**Comment by thinkwee** [comment]
please see wiki [here](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#customization) for customization. You need to customize the RoleConfig.json and add your new employee prompt. You may also need to add your own phase function to assign this new employee.

**Comment by irtiq7** [comment]
That's great. Thanks!
