### ISSUE TITLE
Why is x11 being implemented in the Docker?

### ISSUE THREAD

**Issue by opencoca** [OpenBMB/ChatDev#235]
Adding x11 can lead to complications both with dependencies and security. 

What purpose does it have in the ChatDev docker setup?

**Comment by thinkwee** [comment]
We added x11 because ChatDev needs to execute software with a GUI during the testing phase, which requires x11 to complete the GUI connection between the docker and the host. If you have a safer solution, please let us know, thank you!

**Comment by opencoca** [comment]
Where's the GUI code? I'll look it over. 

It's often best to either expose specific ports or files/folders to connect to.

**Comment by thinkwee** [comment]
> Where's the GUI code? I'll look it over.
> 
> It's often best to either expose specific ports or files/folders to connect to.

This is an AI-powered software generation project. The AI would generate codes using GUI (not in the project code). You need to run this project and the AI will create a main.py and execute it and the Python code may import tkinter/PyQt libraries.

**Comment by opencoca** [comment]
Yes. That's an example of why you might want to expose access to the project via a mount or additional ports.  

Dockers are meant to be self contained and to work without additional tools. If the GUI application is not part of this project then GUI functionality should not be added to this project's docker file. 

As Dockerfiles can source other Dockers a cleaner option would be to have the GUI project's docker build off of this project's docker. This would keep the ChatDev project clean and allow you to expose x11 for your GUI tool.
