### ISSUE TITLE
Add Context and Explanation for 'ChatChainConfig.json' in 'Guides for Customizing ChatDev

### ISSUE THREAD

**Issue by chinmay7016** [OpenBMB/ChatDev#236]
In the "✨️ Advanced Skills" section, there's a reference to "ChatChainConfig.json" in the "Guides for customizing ChatDev" part, but there's no prior mention of where this file can be found or how to use it. This issue aims to provide more context about where to locate the "ChatChainConfig.json" file and how it should be used, making it easier for users to understand how to customize ChatDev.

**Comment by thinkwee** [comment]
Thank you! We have updated the wiki. Please see guide [here](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#customization)
