### ISSUE TITLE
KeyError: incremental_develop

### ISSUE THREAD

**Issue by mooncakedevop** [OpenBMB/ChatDev#248]
Traceback (most recent call last):
  File "/Users/mooncake/gpt/ChatDev/run.py", line 82, in <module>
    chat_chain = ChatChain(config_path=config_path,
  File "/Users/mooncake/gpt/ChatDev/chatdev/chat_chain.py", line 71, in __init__
    incremental_develop=check_bool(self.config["incremental_develop"]))
KeyError: 'incremental_develop'

I print self.config the key incremental_develop is not found

**Comment by wyifei26** [comment]
Thank you for your feedback! There was a small mistake in our previous version, we will fix it right away.

**Comment by wyifei26** [comment]
We have already fix it. Thank you.

**Comment by Mohansolopre** [comment]
I am also getting same error. How to fix it.

**Comment by NA-Wen** [comment]
@Mohansolopre The error has been fixed, try to pull the newest version of ChatDev. 
Hope you enjoy it!
