### ISSUE TITLE
Can you make it easier to install?

### ISSUE THREAD

**Issue by PierrunoYT** [OpenBMB/ChatDev#256]

**Comment by DeflateAwning** [comment]
The installation is extremely standard for Python projects. What specifically was difficult?

**Comment by Alphamasterliu** [comment]
Thank you for your interest in trying out ChatDev😊, we are committed to optimizing our installation process and usage guidelines. If you have any questions about the details feel free to ask.

**Comment by shiloh92** [comment]
Yeah the installation is difficult and I still cant get it to work. Particularly for open source LLMs, as with most projects right now.

**Comment by DeflateAwning** [comment]
What part are you stuck on? What are you trying to install with?

**Comment by ManindraDeMel** [comment]
Have you tried our docker installation and usage process?

**Comment by NA-Wen** [comment]
Thank you for your suggestion! 
We launched ChatDev as a SaaS platform that enables all people to build software efficiently at a very low cost and barrier to entry. You can try it out at https://chatdev.modelbest.cn/. This may save you from the hassle of installing python programs.
