### ISSUE TITLE
Open API Key Error

### ISSUE THREAD

**Issue by symspace** [OpenBMB/ChatDev#259]
Hi Team, 
CEO of Symspace labs here, love what you guys are doing and I'd love to leverage chat dev on my local drive. It seems I continue to run into the same error when attempting to set my Open API key on windos: `(ChatDev_conda_env) C:\Users\zayden>$env:OPENAI_API_KEY="openaikey"
The filename, directory name, or volume label syntax is incorrect.'
Would appreciate any advice or any assistance with this because I have credits in my GPT 4 account. 
Cheers, 
Zayden

**Comment by howtobearealprogrammer** [comment]
Are you running in PowerShell or a windows command terminal ?

I do use something similar in PowerShell.
looks like:

`$env:OPENAI_API_KEY = "blahblahblah"

**Comment by howtobearealprogrammer** [comment]
and please tell me that you did not just publicly post your OPENAI API Key? 🤞

**Comment by Alphamasterliu** [comment]
Hello! when configuring keys in windows you generally have to pay attention to what window it is running in. Generally in Powershell, anaconda, pycharm etc. we can configure the api with $env:OPENAI_API_KEY="your_OpenAI_API_key", but in cmd we need to use the syntax "set " instead of "$env:". Of course, I also suggest that you can configure it directly in your computer's advanced environment variable settings. Thank you very much for your interest in chatdev, if you have any questions please feel free to ask!

**Comment by symspace** [comment]
@howtobearealprogrammer thankfully it was a fake api key haha I'm using windows and anaconda prompt. I just tried setting the open API key in cmd based on @Alphamasterliu suggestions but there was no output so I'm curious as to what the best possible work around would be as a solution. Thank you both for your help btw!

**Comment by kkazantz** [comment]
@symspace the trick that worked for me in a windows is to open the conda navigator and from there run the powershell prompt for my specific environment.
![image](https://github.com/OpenBMB/ChatDev/assets/104065675/3c8c8e25-e15a-4085-8138-db8bed4d55af)
After that just run the $env: OPENAI_API_KEY="[your_OpenAI_API_key]" and you will get no prompt or reply...
![image](https://github.com/OpenBMB/ChatDev/assets/104065675/ebdd844e-49ee-47fd-b10d-3ce97a198b1e)

**Comment by howtobearealprogrammer** [comment]
you can then do something like `dir $env` in powershell which will list out the current session environment variables and you should see your OPENAI_API_KEY variable in the list.

**Comment by symspace** [comment]
@kkazantz @howtobearealprogrammer you guys are the best and I hope you both have a great weekend! I put this on hold because of the new open ai gpt agents and it seems to be producing the same work I needed to do to stay organized; however, it's all in silos. I'd love to hear your thoughts on this!

**Comment by howtobearealprogrammer** [comment]
@symspace - I think the[ Assistant API ](https://platform.openai.com/docs/api-reference/assistants)looks very useful, not sure of your requirements exactly but as something that has access to files (retrieval) and code interpreter whilst still being fully contained inside one environment there are some real upsides.
Hope your weekend was smooth and relaxing 😊

**Comment by bigstrong1024** [comment]
how to set it on ubuntu?
