### ISSUE TITLE
Are you planning to incorporate the bigger GPT-4 Turbo model 

### ISSUE THREAD

**Issue by kkazantz** [OpenBMB/ChatDev#260]
Hi congrats on your fantastic work with ChatDev!
I wanted to ask if you have plans to incorporate the gpt-4-1106-preview (GPT-4 Turbo) model?
With the 128,000 tokens Context window it would be impressive to work with complex tasks with ChatDev and this new beast...

**Comment by phrandsisgo** [comment]
Is it even out yet? And while talking on this topic, how will the custom agents that openAI provide influence the workflow for this ChatDev project?

**Comment by Charuru** [comment]
> Is it even out yet? And while talking on this topic, how will the custom agents that openAI provide influence the workflow for this ChatDev project?

Yes it's out, I don't think the agents are that relevant, they don't offer anything over the agents in this project AFAIK.

**Comment by Charuru** [comment]
This can be closed, look at the latest commits it's been implemented.

**Comment by cenkalti** [comment]
It looks like gpt-4-turbo change is reverted in subsequent commit. I believe this is by mistake when merging in git. Can you take a look please?

https://github.com/OpenBMB/ChatDev/commit/629376976ca6b30b863442644319318966dd4e33
