### ISSUE TITLE
Project Files location

### ISSUE THREAD

**Issue by brown7477** [OpenBMB/ChatDev#261]
I have been experimenting with ChatDev and like it so far, but in my last experiment I am not able to find the files according to the [manual.md](https://github.com/brown7477/CultiTool3_DefaultOrganization_20231106150302/blob/main/manual.md).
For some reason it tells me to `git clone https://github.com/ChatDev/CannabisStrainsAggregator.git` then some other commands.
If I am running this locally, where are the newly created files going?

**Comment by tdicusmurray** [comment]
chatdev/warehouse/ this folder.

**Comment by brown7477** [comment]
Sorry, There are only a few files there. Here is everything from the Folder.
[https://github.com/brown7477/CultiTool3_DefaultOrganization_20231106150302](https://github.com/brown7477/CultiTool3_DefaultOrganization_20231106150302)

**Comment by howtobearealprogrammer** [comment]
what does your whole command line look like? specifically the parts after `python run.py --task "words"` 
Also if it's generating git info you may have the git option turned on which, for me at least, I left until after I had the basic bit going.

I may be wrong here but if you have something like this:

`python run.py --task "print words" --name "wordprinter" --org "wordorg" --[all the other options here]`

It will generate it's output in a new folder under the `\WAREHOUSE` folder named something like wordprinter_wordorg_timestamp so I would have a folder structure that looks a little like this:

`\main folder\WAREHOUSE\wordprinter_wordorg_timestamp`

**Comment by NA-Wen** [comment]
The software output folder lies under the folder `WareHouse`. The whole path is like `\ChatDev\WareHouse\CultiTool3_DefaultOrganization_20231106150302`.
And `git management` just did some additional git command for the software folder. If this confused you, our wiki https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#git-mode might help.
