### ISSUE TITLE
"incremental"  only working for python file (main.py)

### ISSUE THREAD

**Issue by rafaelconcept** [OpenBMB/ChatDev#268]
I asked to create an HTML page, it created it correctly, but the increment doesn't work because it doesn't find the py file

**Comment by howtobearealprogrammer** [comment]
@rafaelconcept - you will need to change the code to enable it to import more than just `.py` files.

In chatdev\codes.py you will need to alter the `_load_from_hardware` module (for me this is around line 219 but I have altered my codes.py file significantly

You are looking for this conditional:

```
if filename.endswith(".py"):
    filepath = os.path.join(root,filename)
```

You will want to update/change the filename.endswith to also include the other extensions you desire.

To "brute force" solve your specific need I would change it to:
```
if filename.endswith((",py",".html")):
````


there are more elegant ways to solve this for a greater array of file types but this is the reason why it errors and a rough fix

**Comment by omarigg04** [comment]
In my case its not working even for the .py files im just keep getting this error:

FileNotFoundError: [WinError 3] The system can not find the specifiedpath: 'C:\\Users\\omarigg\\Desktop\\ChatDev\\ChatDev\\WareHouse\\Gomoku_DefaultOrganization_20231114015700\\base'

Im executing like this:
python run.py --task "[when face is detected a message appear on the screen]" --config "incremental" --path "[WareHouse\faceAppIncremental\main.py]"

**Comment by howtobearealprogrammer** [comment]
@omarigg04 - in my case I have specified out the entire path for my incremental source folder so mine is a little like:

```
python run.py --task "the task" -- config "incremental" --path "c:\users\myusername\documents\chatdevSource\"
```

In your case that might be like:
``` 
python run.py [insert all other things here] --path "C:\Users\omarigg\Desktop\ChatDev\ChatDev\WareHouse\faceAppIncremental\"
```

Hope helps 😸

**Comment by NA-Wen** [comment]
@omarigg04 Try to use:
`python run.py [insert all other things here] --path "WareHouse\faceAppIncremental"`
or 
`python run.py [insert all other things here] --path "{the absolute path of faceAppIncremental}"`
In a word, the path parameter should be a folder path of your sofrware, not just a .py file.
