### ISSUE TITLE
How do I use this without conda?

### ISSUE THREAD

**Issue by JiaCYu** [OpenBMB/ChatDev#272]
I don't know how to set the environmental variables without conda.

**Comment by howtobearealprogrammer** [comment]
`Pyenv` is the tool you want. You will have to download the version of Python you need but the docs are fairly straight forward to follow. I had Python 3.bignumber initially and could not get conda to work for me (missed the `conda init powershell` that is needed if one is using conda inside powershell) so I ended up using `Pyenv` to configure the environment.

This also does work with vscode debugging btw but it is a mess and you're better to use conda if you want to do that kind of work (imo)

I think all that conda is really doing is ensuring that the environment is running the correct version of python as there are breaking changes when you move off 3.9.x

If you're on a windows machine this is the [Pyenv for Windows](https://github.com/pyenv-win/pyenv-win) repo.

Hope helps 😸

**Comment by JiaCYu** [comment]
Thanks for the suggestion, but I should have clarified before that we're not allowed to use any tool like conda or pyenv :(
Is there a way to hard code the environmental variables, like have an .env file?

**Comment by JiaCYu** [comment]
#116 Oh I found the answer here
