### ISSUE TITLE
生成2048游戏，运行界面是白板，如何排查

### ISSUE THREAD

**Issue by wangyuelucky** [OpenBMB/ChatDev#275]
1. [参考文档](https://github.com/OpenBMB/ChatDev/blob/main/readme/README-Chinese.md)配置环境
  - chatdev版本
```
commit adcda972d08aec41e1d93f92073ae135c4fc17f7 (HEAD -> main, origin/main, origin/HEAD)
```

  - python version 3.10.5
```
python -V
Python 3.10.5
```
  - os 信息
```
Darwin Q422J3PY9P 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023;  arm64
```

2. 执行构建软件命令
```
python3 run.py --task "design a 2048 game" --name "2048" --org "THUNLP" --config "Default"
```

3. 生成结果
截取了最后几行内容
```
Software Info:

💰**cost**=$0.033161

🔨**version_updates**=5.0

📃**num_code_files**=2

🏞**num_png_files**=0

📚**num_doc_files**=7

📃**code_lines**=119

📋**env_lines**=1

📒**manual_lines**=47

🗣**num_utterances**=26

🤔**num_self_reflections**=1

❓**num_prompt_tokens**=15059

❗**num_completion_tokens**=5286

🌟**num_total_tokens**=20345

🕑**duration**=713.00s

ChatDev Starts (20231117171431)

ChatDev Ends (20231117172624)

/Users/xxx/workspace/ChatDev/WareHouse/2048_DefaultOrganization_20231117171431/__pycache__ Removed.
```

4. 问题：运行游戏 界面白板 如下图
python main.py
![screenshot-20231117-165830](https://github.com/OpenBMB/ChatDev/assets/1996279/cf9c7577-d313-4381-98a1-9d48f2bc3d05)

**Comment by howtobearealprogrammer** [comment]
这是chatdev的一个常见问题，不容易解决。如果你加入了人工代理步骤，你可以告诉它用户界面没有显示。
否则，解决方案是在之后手动修改python文件。
Chatdev并不完美。

**Comment by howtobearealprogrammer** [comment]
我使用了chatgpt来进行中文翻译，如果有误请原谅。

😻

**Comment by NA-Wen** [comment]
Thank you for your feedback. Due to the limited capacity of LLM, sometimes the output software may not work well. You can try:
1. try again using the same prompt
2. use our new developed feature `incremental development` to develop upon the generated code
3. modify the code by yourself is also a way to solve

**Comment by wangyuelucky** [comment]
@howtobearealprogrammer @NA-Wen 
Thank you for your reply. 
Is there an example that can run smoothly from end to end? Is 2048 game too complicated?

**Comment by howtobearealprogrammer** [comment]
@wangyuelucky - from my experience so far not really. I have built 14 different iterations of a calculator app and 18 different "Todo List" applications. Sometimes it gets the UI right but then makes a silly error (like 1+1=error) or all the code is present but it "forgets" to actually display the UI.

In my opinion it is a very powerful starting tool but it is not a complete replacement.
I have found that using the `human` company model will allow you to tell it that the UI is not displaying and it will fix it and as @NA-Wen says the `incremental development` option is also a very useful way to solve it if you already have a shell app with a UI.

or you can take the first output you got and then do something like this:

put first version (with no UI) in a source folder, for example \Source\thecode\ 
then run chatdev again with a command line like `--task "add a GUI to this application" --path "\Source\thecode\" ` with incremental development turned on in your company config.

*note that my example command line will not run as it stands and you will need to alter this to suit your environment

Hope Helps 😻

**Comment by NA-Wen** [comment]
> @howtobearealprogrammer @NA-Wen Thank you for your reply. Is there an example that can run smoothly from end to end? Is 2048 game too complicated?

According to my experience of using ChatDev, 2048 game seems not go beyond its capability. You can find some good software examples and their prompts in our [WareHouse](https://github.com/OpenBMB/ChatDev/tree/main/WareHouse). Hope these helps. 
And if you have created some excellent software using ChatDev,  you are encouraged to share your work with us by making a pull request😀!

**Comment by wangyuelucky** [comment]
Thanks for the suggestion, i will try again
