### ISSUE TITLE
Add support for GPT-4-Turbo

### ISSUE THREAD

**Issue by danbiocchi** [OpenBMB/ChatDev#284]
Can't do anything with 3.5 turbo. The code it makes is brutal. Can it be possible to Add GPT 4 Turbo? gpt-4-1106-preview

**Comment by rolltidehero** [comment]
There is currently a pull request awaiting a bug fix and then I think they will push it through.
https://github.com/OpenBMB/ChatDev/pull/277

**Comment by standrze** [comment]
> There is currently a pull request awaiting a bug fix and then I think they will push it through. #277

roll tide
