### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by renatokuipers** [OpenBMB/ChatDev#29]
When I follow all the steps and set up a Conda env, I can't seem to execute the application. After I enter my product Idea and the product name, it comes back with:

Traceback (most recent call last):
  File "E:\ChatDeveloper\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "E:\ChatDeveloper\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "E:\ChatDeveloper\ChatDev\camel\agents\__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "E:\ChatDeveloper\ChatDev\camel\agents\chat_agent.py", line 24, in <module>
    from camel.model_backend import ModelBackend, ModelFactory
  File "E:\ChatDeveloper\ChatDev\camel\model_backend.py", line 21, in <module>
    from chatdev.utils import log_and_print_online
  File "E:\ChatDeveloper\ChatDev\chatdev\utils.py", line 9, in <module>
    from online_log.app import send_msg
  File "E:\ChatDeveloper\ChatDev\online_log\app.py", line 5, in <module>
    from flask import Flask, send_from_directory, request, jsonify
ModuleNotFoundError: No module named 'flask'

I did a pip list and this is the result:

(ChatDev_conda_env) E:\ChatDeveloper\ChatDev>pip list
Package               Version
--------------------- --------
aiohttp               3.8.4
aiosignal             1.3.1
astroid               2.15.0
async-timeout         4.0.2
attrs                 23.1.0
autopep8              1.6.0
bidict                0.22.1
blinker               1.6.2
certifi               2023.5.7
cfgv                  3.3.1
charset-normalizer    3.1.0
click                 8.1.6
colorama              0.4.6
dill                  0.3.6
distlib               0.3.6
docstring-to-markdown 0.11
filelock              3.12.2
flake8                6.0.0
Flask                 2.3.2
Flask-SocketIO        5.3.4
frozenlist            1.3.3
identify              2.5.24
idna                  3.4
importlib-metadata    6.8.0
install               1.3.5
isort                 5.12.0
itsdangerous          2.1.2
jedi                  0.18.2
jieba                 0.42.1
Jinja2                3.1.2
lazy-object-proxy     1.9.0
Markdown              3.4.4
MarkupSafe            2.1.3
mccabe                0.7.0
multidict             6.0.4
nodeenv               1.8.0
numpy                 1.24.3
openai                0.27.8
packaging             23.0
parso                 0.8.3
Pillow                9.5.0
pip                   23.2.1
platformdirs          3.5.3
pluggy                1.2.0
pre-commit            3.3.3
pycodestyle           2.10.0
pydocstyle            6.2.3
pyflakes              3.0.1
pygame                2.5.1
pylint                2.17.0
PySocks               1.7.1
python-engineio       4.5.1
python-lsp-jsonrpc    1.0.0
python-lsp-server     1.7.1
python-socketio       5.8.0
pytoolconfig          1.2.5
PyYAML                6.0
regex                 2023.6.3
requests              2.31.0
retrying              1.3.4
rope                  1.7.0
setuptools            68.0.0
six                   1.16.0
snowballstemmer       2.2.0
tenacity              8.2.2
tiktoken              0.4.0
timeout-decorator     0.5.0
toml                  0.10.2
tomli                 2.0.1
tomlkit               0.11.6
tqdm                  4.65.0
typing_extensions     4.5.0
ujson                 5.7.0
urllib3               2.0.3
virtualenv            20.23.0
Werkzeug              2.3.6
whatthepatch          1.0.4
wheel                 0.38.4
wrapt                 1.15.0
yapf                  0.32.0
yarl                  1.9.2
zipp                  3.16.2

Whats going wrong?

**Comment by renatokuipers** [comment]
Yeah... I already did that... look at the list of all the installed Pip packages :)
But I still have the same issue..

If its any important information, I work in Windows, not in Linux/MacOS.

Maybe thats a thing that causes this issue?

**Comment by lijiahao2022** [comment]
Try set up your python environment to Python version 3.10.12 with the command:
`conda create -n ChatDev_conda_env python=3.10.12`
instead of
`conda create -n ChatDev_conda_env python=3.9 -y`
