### ISSUE TITLE
[Suggestion] Rename `online_log` to `chat_visualizer`

### ISSUE THREAD

**Issue by DeflateAwning** [OpenBMB/ChatDev#291]
It's not clear what "online_log" means. If you named it Chat Visualizer or Chat Viewer, that would be way more clear

**Comment by suhasasumukh** [comment]
@qianc62 @DeflateAwning you can close this issue

**Comment by thinkwee** [comment]
We will change the code. In the first online_log is only served for visualizing the real-time log during the software generation.  Then we unify all the visualization modules in the same self-host website and put all the codes under this path.

**Comment by DeflateAwning** [comment]
I will close the issue once the issue is resolved. The `master` branch still has it in a folder named `online_log`, which is not representative of what that folder contains.

**Comment by cocobeach** [comment]
> I will close the issue once the issue is resolved. The `master` branch still has it in a folder named `online_log`, which is not representative of what that folder contains.

It means chat_visualizer, but you know it, I know it, and everybody knows it, especially the code that breaks without it.

**Comment by DeflateAwning** [comment]
It should be renamed. That is why there is an issue. 

Not everyone knows it. I wasted time figuring out what it was/did. That is why this issue to fix it exists.

**Comment by thinkwee** [comment]
We have renamed online_log --> visualizer, and add some introduction on md and code.
Please see https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#visualizer, https://github.com/OpenBMB/ChatDev/blob/main/chatdev/utils.py#L16.

**Comment by DeflateAwning** [comment]
Good stuff! Would have been best if this issue was tagged in the associated [commit](https://github.com/OpenBMB/ChatDev/commit/6ff2e8f921fe047b03d7e6d4f6533c743c18f928) or PR. Thanks!

**Comment by jaredkipe** [comment]
Looks like you missed some stuff.  When doing a plain old 'run' it tries to import from old missing module
