### ISSUE TITLE
No module named "tenacity"

### ISSUE THREAD

**Issue by mosobln** [OpenBMB/ChatDev#30]
Anyone facing the same issue when executing the idea and project name? I installed Conda env all requirements are satisfied. 

  File "C:\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "C:\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "C:\ChatDev\camel\agents\__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "C:\ChatDev\camel\agents\chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'

**Comment by hemangjoshi37a** [comment]
```
pip install tenacity
```

**Comment by mosobln** [comment]
Sorry forgot to mention that all packages are installed 🙃

**Comment by TashaSkyUp** [comment]
`
(ChatDev_conda_env) E:\git\ChatDev>pip install tenacity
Collecting tenacity
  Obtaining dependency information for tenacity from https://files.pythonhosted.org/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.
3-py3-none-any.whl.metadata
  Downloading tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Installing collected packages: tenacity
Successfully installed tenacity-8.2.3

(ChatDev_conda_env) E:\git\ChatDev>python3 run.py --task "[description_of_your_idea]" --name "[project_name]"
Traceback (most recent call last):
  File "E:\git\ChatDev\run.py", line 19, in <module>                    
    from camel.typing import ModelType                                  
  File "E:\git\ChatDev\camel\__init__.py", line 14, in <module>         
    import camel.agents                                                 
  File "E:\git\ChatDev\camel\agents\__init__.py", line 15, in <module>  
    from .chat_agent import ChatAgent                                   
  File "E:\git\ChatDev\camel\agents\chat_agent.py", line 17, in <module>
    from tenacity import retry                                          
ModuleNotFoundError: No module named 'tenacity'                         

(ChatDev_conda_env) E:\git\ChatDev>
`

**Comment by TashaSkyUp** [comment]
Oh I know what it is... On windows sometimes you can end up with a "python3.exe" somewhere else on your system. But when You make a venv (apparent even in conda) you get a python.exe. the same is not true in linux. so linux devs will forget to remove the 3 for the run command. so use

`python run.py --task "[description_of_your_idea]" --name "[project_name]"`

NOT

`python3 run.py --task "[description_of_your_idea]" --name "[project_name]"`

at least on windows

**Comment by hemangjoshi37a** [comment]
> Oh I know what it is... On windows sometimes you can end up with a "python3.exe" somewhere else on your system. But when You make a venv (apparent even in conda) you get a python.exe. the same is not true in linux. so linux devs will forget to remove the 3 for the run command. so use
> 
> `python run.py --task "[description_of_your_idea]" --name "[project_name]"`
> 
> NOT
> 
> `python3 run.py --task "[description_of_your_idea]" --name "[project_name]"`
> 
> at least on windows

@TashaSkyUp 

In fact you should always run every command with `python3` instead `python` every time in your life. That is a good practice I think.

**Comment by TashaSkyUp** [comment]
"python3.exe" does  not exist when you create the conda environment in windows.


```
(ChatDev_conda_env) E:\git\ChatDev\WareHouse\caption me_DefaultOrganization_20230910183821>where python3
C:\Users\Tasha\AppData\Local\Microsoft\WindowsApps\python3.exe

(ChatDev_conda_env) E:\git\ChatDev\WareHouse\caption me_DefaultOrganization_20230910183821>where python
C:\Users\Tasha\.conda\envs\ChatDev_conda_env\python.exe
C:\Python310\python.exe
C:\Users\Tasha\AppData\Local\Microsoft\WindowsApps\python.exe
```

So in fact for windows you get the error I mentioned and detailed above.

**Comment by Gambit-Play** [comment]
![chatDev-error-1](https://github.com/OpenBMB/ChatDev/assets/22627768/c3a81f0c-0489-4781-a685-baeab6993c35)

I'm getting the same error too

**Comment by paulie-rodriguez** [comment]
@mosobln were you able to resolve this?
