### ISSUE TITLE
[Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}

### ISSUE THREAD

**Issue by yashkite** [OpenBMB/ChatDev#301]
[SlitherMe_DefaultOrganization_20231216131424.log](https://github.com/OpenBMB/ChatDev/files/13691736/SlitherMe_DefaultOrganization_20231216131424.log)

> [2023-12-16 13:16:26.307] [INFO] [LM STUDIO SERVER] Processing queued request...
> [2023-12-16 13:16:26.308] [INFO] Received POST request to /v1/chat/completions with body: {
>   "messages": [
>     {
>       "role": "system",
>       "content": "ChatDev is a software company powered by multiple intelligent agents, such as chief executive officer, chief human resources officer, chief product officer, chief technology officer, etc, with a multi-agent organizational structure and the mission of \"changing the digital world through programming\".\nYou are Chief Product Officer. we are both working at ChatDev. We share a common interest in collaborating to successfully complete a task assigned by a new customer.\nYou are responsible for all product-related matters in ChatDev. Usually includes product design, product strategy, product vision, product innovation, project management and product marketing.\nHere is a new customer's task: Build an Android Studio Snake game named 'SlitherMe' with classic gameplay. The player controls a snake that grows by eating food while avoiding collisions. Implement scoring, user interface, animations, and optimize for various screen sizes..\nTo complete the task, you must write a response that appropriately solves the requested instruction based on your expertise and customer's needs."
>     },
>     {
>       "role": "user",
>       "content": "ChatDev has made products in the following form before:\n\nImage: can present information in line chart, bar chart, flow chart, cloud chart, Gantt chart, etc.\n\nDocument: can present information via .docx files.\n\nPowerPoint: can present information via .pptx files.\n\nExcel: can present information via .xlsx files.\n\nPDF: can present information via .pdf files.\n\nWebsite: can present personal resume, tutorial, products, or ideas, via .html files.\n\nApplication: can implement visualized game, software, tool, etc, via python.\n\nDashboard: can display a panel visualizing real-time information.\n\nMind Map: can represent ideas, with related concepts arranged around a core concept.\n\nAs the Chief Product Officer, to satisfy the new user's demand and the product should be realizable, you should keep discussing with me to decide which product modality do we want the product to be?\n\nNote that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word <INFO>, followed by our final product modality without any other words, e.g., \"<INFO> PowerPoint\"."
>     },
>     {
>       "role": "assistant",
>       "content": "\n\nOnce we have decided on the product modality, I will create a new task for you to complete it.\n\nIf you are not sure about the product modality, please ask me to clarify and discuss with me again.\n\nNote that this is a teamwork task, so please let's work together to solve the problem.\n\nGood luck!"
>     },
>     {
>       "role": "user",
>       "content": ""
>     },
>     {
>       "role": "user",
>       "content": ""
>     },
>     {
>       "role": "user",
>       "content": ""
>     },
>     {
>       "role": "user",
>       "content": ""
>     },
>     {
>       "role": "user",
>       "content": ""
>     }
>   ],
>   "model": "gpt-3.5-turbo-16k-0613",
>   "temperature": 0.2,
>   "top_p": 1,
>   "n": 1,
>   "stream": false,
>   "stop": null,
>   "max_tokens": 15739,
>   "presence_penalty": 0,
>   "frequency_penalty": 0,
>   "logit_bias": {},
>   "user": ""
> }
> [2023-12-16 13:16:26.308] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}

**Comment by yashkite** [comment]
After Working with the smaller model don't give this error

**Comment by Zer0445** [comment]
[2024-05-29 12:35:43.230] [ERROR] [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}
