### ISSUE TITLE
Hardcoded chatdev_prompt_template 

### ISSUE THREAD

**Issue by zwilch** [OpenBMB/ChatDev#302]
There is a hard coded template about the company information:
chatdev_prompt_template = "ChatDev is a software company powered by multiple intelligent agents, such as chief executive officer, chief human resources officer, chief product officer, chief technology officer, etc, with a multi-agent organizational structure and the mission of \"changing the digital world through programming\"."
in 
https://github.com/OpenBMB/ChatDev/blob/b56de45e0e6aeb5f915c4e1e3e8918c852248ea3/camel/agents/role_playing.py#L134
I want use my onw company and have created a new folder and use "--config". But chatdev_prompt_template is not overrided.
**Can it be moved into the ChatChainConfig.json to specifi a new company in the own "--config"?**
chatdev_prompt_template comes to "company":" ...."  in ChatChainConfig.json

Example CompanyConfig/Default/ChatChainConfig.json
```
{ "company":"ChatDev is a software company ... .... .... ... ",
  "chain": [
    {
      "phase": "DemandAnalysis",
      "phaseType": "SimplePhase",
      "max_turn_step": -1,
      "need_reflect": "True"
    },

```

**Comment by thinkwee** [comment]
yes, we forgot the customization on the company information. we will change the configure soon.

**Comment by thinkwee** [comment]
please refer to https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#chatchain-parameters, we add a background_prompt parameter
