### ISSUE TITLE
A couple of inquiries regarding CompanyConfig

### ISSUE THREAD

**Issue by mrpwoodz** [OpenBMB/ChatDev#305]
Hello, firstly allow me to say that ChatDev is an amazing application with so much potential since it is only the end of 2023. I was going through the CompanyConfig settings and want to incorporate as many features into the development process as possible, but I have a few things to ask about beforehand so I best understand:

- For "incremental_develop", I'm a bit confused on whether or not it can be ran within the Human configuration? Because I see it listed as an option in the Human ChatChainConfig file, yet Increment is a separate folder with it's own ChatChainConfig. I would love to combine both to experiment with results.

- For "brainstorming", is there any additional setup required to set this up? I changed it to "True" and was having some issues running it, but I did have other errors that I created when editing the structure that were fixed after redownloading. I am going to attempt to run it now with a fresh functional ChatDev but thought I would still ask just incase.

- I would really like to know if Docker is necessary for advanced gui programs or something? The Docker section seems a bit vague in whether I should or shouldn't utilize it. I didn't want to install it if it won't be useful but if it helps with running more visually complex software then that definitely helps.

EDIT: Can I combine the functions of Human/Increment/Art configurations?

I really appreciate the help, have a great rest of your weeks.

**Comment by thinkwee** [comment]
Thank you for your advice!
1. incremental_develop: incremental_develop is coded based on the Human mode, we will consider unifying these two configurations.
2. brainstorming: please ignore it. It was an early design, now deprecated. We will remove this option.
3. docker: you can try advanced GUI programs in command style. Docker is only used for safer execution.
