### ISSUE TITLE
Integretion of MemGPT for more context

### ISSUE THREAD

**Issue by yashkite** [OpenBMB/ChatDev#307]
If we use MemGPT while when chat dev builds the app it can provide greater context if it gets misled during  process

**Comment by thinkwee** [comment]
Yes, many exciting agent-related projects have been coming out recently. But we're not going to integrate all of these projects. Everyone is welcome to try modifying ChatDev yourself and share your experience😄 ~

**Comment by madsamjp** [comment]
I second this. I think this is going to be essential for many LLM agent related projects going forward.  16k context windows is massively restrictive when working on larger or more complex projects. A more efficient use of the context window will provide many benefits.

**Comment by yashkite** [comment]
> Yes, many exciting agent-related projects have been coming out recently. But we're not going to integrate all of these projects. Everyone is welcome to try modifying ChatDev yourself and share your experience😄 ~

I never did anything like this, i know a little bit of coding related to Android apps development and a little bit of python, if I'm able to do this then I will open the pull request for a new branch so any new members can try it and develop further

**Comment by Alphamasterliu** [comment]
Thank you again for your suggestions for ChatDev! 😆
Expanding the context length limit or considering how to truncate text seems to be an ongoing issue in the NLP field. We are also pleasantly surprised to find that OpenAI has been continuously updating, especially in terms of text length limitations which have been significantly extended. 
As a result, we are now focusing more on research that aligns with our Multi-Agent collaboration. Of course, your idea of referencing other Agents or Models and integrating them into ChatDev is very noteworthy, as making its functionalities more comprehensive and stable is our ongoing goal. Please look forward to our future updates.
