### ISSUE TITLE
Issues with OPENAI_API_KEY and OPENAI_API_BASE in the Latest Update

### ISSUE THREAD

**Issue by yashkite** [OpenBMB/ChatDev#312]
in newer update

set OPENAI_API_KEY=sk-dummy1234
set OPENAI_API_BASE=http://localhost:1234/v1

These commands are not taking effect. Instead of communicating with the local server, they are trying to connect to the open-ai website.

**Comment by thinkwee** [comment]
We do not officially support self-built models, please refer to https://github.com/OpenBMB/ChatDev/issues/27

The new openai api supports base url, but this is only used to forward requests to openai, not for a self-built service. You can return to the old version of openai api (still compatible in ChatDev) or discuss the self-built service issues in the new openai api in our [discord](https://discord.com/invite/bn4t2Jy6TT).

**Comment by yashkite** [comment]
Thanks


For me it wasn't OPENAI_API_BASE, but BASE_URL.
After setting this, everything works fine with LiteLLM + Ollama

Found this comment and it worked

**Comment by hemangjoshi37a** [comment]
If anyone has ollama working with this then please let me know how to do this . thanks .
