### ISSUE TITLE
KeyError: 'web_spider'    when trying to run run.py

### ISSUE THREAD

**Issue by djbritt** [OpenBMB/ChatDev#318]
I get this when I run run.py

I've reinstalled all the modules, used conda, nothing is helping.
```
Traceback (most recent call last):
  File "/Users/djbritt/Downloads/ai/gamedev/update_12.31.23/ChatDev/run.py", line 102, in <module>
    chat_chain = ChatChain(config_path=config_path,
  File "/Users/djbritt/Downloads/ai/gamedev/update_12.31.23/ChatDev/chatdev/chat_chain.py", line 66, in __init__
    self.web_spider = self.config["web_spider"]
KeyError: 'web_spider'
```

**Comment by jeffhaskin** [comment]
It seems to be something to do with `--config "Human"`

I have found that:
`python3 run.py --task "[description_of_your_idea]" --name "[project_name]"`
...will work fine, while:
`python3 run.py --task "[description_of_your_idea]" --name "[project_name]" --config "Human"`
returns the KeyError: 'web_spider'

**Comment by yu-shaonian** [comment]
yes, it lacks something in the Human and Art config file. We will fix it quick
