### ISSUE TITLE
python3 run.py --task "[chat-dev]" --name "[test]"

### ISSUE THREAD

**Issue by 2315572878** [OpenBMB/ChatDev#32]
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6cf61d7a60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /v1/chat/completions

**Comment by lijiahao2022** [comment]
Thank you for your feedback. Could you please describe the error in more detail？
