### ISSUE TITLE
Requirements text file missing bs4

### ISSUE THREAD

**Issue by jeffhaskin** [OpenBMB/ChatDev#320]
The program requires bs4 but bs4 isn't in the requirements.txt file so it doesn't get installed and the program won't run.

The user has to manually run `pip3 install bs4` to make the program work but lots of users are in way over their head and won't figure that out (it took me forever).

**Comment by thinkwee** [comment]
@yu-shaonshao

**Comment by DonFelidae** [comment]
hi! esto funciono para mi:
pip3 install BeautifulSoup4

**Comment by thinkwee** [comment]
it is introduced in the web_spyder feature, please add the requirement. @yu-shaonian
