### ISSUE TITLE
Log Visualizer doesn't show anything in home page

### ISSUE THREAD

**Issue by Wenbobobo** [OpenBMB/ChatDev#332]
I followeed the doc and use "python visualizer/app.py" in Whindows
Then I got blank in the first page instead of log Visualizing:
<img width="1280" alt="屏幕截图 2024-01-15 215608" src="https://github.com/OpenBMB/ChatDev/assets/78262508/1103a0b6-9095-4535-8454-2b03d6009be1">
But when I upload the log in replay.html, I can replay them normally, but not so detailed
<img width="1280" alt="屏幕截图 2024-01-15 215544" src="https://github.com/OpenBMB/ChatDev/assets/78262508/644858e0-3064-492b-9972-cb68dc990bf6">
I didn't find an upload button in the home page....Did I miss anything?
thx for any reply

**Comment by Wenbobobo** [comment]
> I didn't find an upload button in the home page....Did I miss anything?

Oh, It suddenly worked. Maybe it needs to start in a certain order rather than let Flask wait (maybe you can remind it in the Doc) ... 

By the way, when using the “Human” mode, it seems that the modified code will be directly given to humans by default, but currently GPTs often find it difficult to provide code that can be run directly and require testing. It's usually necessary to help with 
 debugging AI code 😂

### By the way, Is it possible to drag directly in the visualizerGUI to change the order of ChatChains? I think this will greatly increase convenience and truly allow everyone to create their own ChatChains 🚀

Very good project, I hope to continue cheering 😘

**Comment by thinkwee** [comment]
Please see https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#visualizer for more guides.
The log visualizer won't display anything until you start building software using ChatDev by running ``python3 main.py``. It displays real-time logs for the running ChatDev.
The replay visualizer only replays the agent dialogue, it would not contain detailed information in the log.
The log visualizer is used for debugging while the replay visualizer is used for a quick peak on others' logs.

As for dragging directly in some UI to customize the ChatChain, you can try our SaaS service at: https://chatdev.modelbest.cn/login

Thank you for your support!
