### ISSUE TITLE
Poker is bogus

### ISSUE THREAD

**Issue by TomSB1423** [OpenBMB/ChatDev#346]
Poker accepts negative numbers for bets

> 
> Human posted blind of 10. Remaining chips: 990
> AI 4 posted blind of 5. Remaining chips: 995     
> Pot: 15
> AI 1 called 10. Remaining chips: 990
> AI 2 folded.
> AI 3 called 10. Remaining chips: 990
> Raise increment: 50
> AI 4 raised an additonal 65. Remaining chips: 930
> Current top bet is: 70
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: []
> Enter your decision (fold/check/bet/call/raise): raise 100
> Invalid decision. Please enter a valid decision. 
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: []
> Enter your decision (fold/check/bet/call/raise): raise
> Enter the raise amount: 140 + 100
> Human raised an additonal 230. Remaining chips: 760
> Current top bet is: 240
> AI 1 folded.
> AI 3 called 230. Remaining chips: 760
> AI 4 called 170. Remaining chips: 760
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades']
> Pot: 730
> Raise increment: 74
> AI 3 raised an additonal 74. Remaining chips: 686
> Current top bet is: 74
> AI 4 folded.
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades']
> Enter your decision (fold/check/bet/call/raise): raise
> Enter the raise amount: 148 + 760
> Human raised an additonal 908. Remaining chips: -148
> Current top bet is: 908
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades', 'Q of Hearts']
> Pot: 1712
> Raise increment: 76
> AI 3 raised an additonal 76. Remaining chips: 610
> Current top bet is: 76
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades', 'Q of Hearts']
> Enter your decision (fold/check/bet/call/raise): bet
> Invalid decision. Please enter a valid decision.
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades', 'Q of Hearts']
> Enter your decision (fold/check/bet/call/raise): raise
> Enter the raise amount: 152 + -148
> Human raised an additonal 4. Remaining chips: -152
> Current top bet is: 4
> AI 3 called -72. Remaining chips: 682
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades', 'Q of Hearts', 'K of Spades']
> Pot: 1720
> AI 3 checked.
> Your cards: Q of Diamonds, 4 of Hearts
> Community cards: ['9 of Spades', 'A of Clubs', 'Q of Spades', 'Q of Hearts', 'K of Spades']
> Enter your decision (fold/check/bet/call/raise): raise        
> Enter the raise amount: 0 + -100000
> Human raised an additonal -100000. Remaining chips: 99848
> Current top bet is: -100000
> Human with cards: ['Q of Diamonds', '4 of Hearts'] has hand value: 162
> AI 3 with cards: ['J of Hearts', '6 of Hearts'] has hand value: 1428
> AI 3 wins with Unknown!
> Pot: 0
> AI 1 folded.
> AI 2 called 10. Remaining chips: 990
> AI 4 called 10. Remaining chips: 750
> Your cards: 3 of Diamonds, Q of Clubs
> Community cards: []
> Enter your decision (fold/check/bet/call/raise): check
> Human checked.
> Raise increment: 55
> AI 2 raised an additonal 65. Remaining chips: 925
> Current top bet is: 75
> Raise increment: 12
> AI 4 raised an additonal 152. Remaining chips: 598
> Current top bet is: 162
> Your cards: 3 of Diamonds, Q of Clubs
> Community cards: []
> Enter your decision (fold/check/bet/call/raise): fold
> Human folded.

**Comment by Alphamasterliu** [comment]
Hello! 😆
Thank you very much for trying out the product created with our software. The Poker game was created and contributed by users through ChatDev, and we have collected such interesting ideas in our Warehouse. Of course, there may be some flaws, which I think are acceptable because generative AI is inherently random. We greatly appreciate and respect the efforts of every user. If you would like to improve this software, I suggest downloading Poker to your local machine and then continuing to optimize it using the "incremental development" mode `--config "incremental" --path "[source_code_directory_path]` we have previously opened up. Thank you very much for your attention!
