### ISSUE TITLE
How to re run already ran project?

### ISSUE THREAD

**Issue by hemangjoshi37a** [OpenBMB/ChatDev#35]
I have created a project named `Flippers` that is named `Flippers_DefaultOrganization_20230909143816` as folder now I want to re run this with chatDev. How to do this ? What I mean is I want to continue development further from available code from previous run of chatDev or my personal manually made project.

**Comment by renatokuipers** [comment]
As far as I read and understand the sourcecode, this functionality is not implemented.
Maybe there is a possibility for the devs (creators of this repo ;) ) to implement this into ChatDev

**Comment by lijiahao2022** [comment]
Thank you for your feedback. At present, ChatDev does not support incremental development, and this feature will be supported in the future, so stay tuned

**Comment by lijiahao2022** [comment]
Thank you for your feedback. At present, ChatDev does not support incremental development, and this feature will be supported in the future, so stay tuned

**Comment by lijiahao2022** [comment]
Thank you for your feedback. 
ChatDev does not support incremental development currently, and this feature will be supported in the future, so please stay tuned .
