### ISSUE TITLE
The system cannot find the path specified in Install Dependencies:

### ISSUE THREAD

**Issue by Kanuj7** [OpenBMB/ChatDev#350]
The system cannot find the path specified in Install Dependencies: please help me regarding solving this issue  
![install dependencies in visual studios](https://github.com/OpenBMB/ChatDev/assets/159071138/f957a3a6-8811-49e1-8f1b-e7b8b9b0a0f9)

**Comment by Alphamasterliu** [comment]
Hi, according to your path display, you have actually entered the ChatDev-main folder and activated the conda environment, so you don't need to cd into ChatDev again.

**Comment by Kanuj7** [comment]
C

> Hi, according to the path you've shared, you have actually entered the ChatDev-main folder before activating the conda environment, so there's no need to cd into ChatDev again. This is because you can see that the run.py file, which needs to be executed with Python in the next step, is located in the ChatDev-main folder.

Could You please briefly explain this to me ?

**Comment by Alphamasterliu** [comment]
In short, you can skip the step in your third line.

> > Hi, according to the path you've shared, you have actually entered the ChatDev-main folder before activating the conda environment, so there's no need to cd into ChatDev again. This is because you can see that the run.py file, which needs to be executed with Python in the next step, is located in the ChatDev-main folder.
> 
> Could You please briefly explain this to me ?

In short, you can skip the step in your third line.

**Comment by Kanuj7** [comment]
> > > Hi, according to the path you've shared, you have actually entered the ChatDev-main folder before activating the conda environment, so there's no need to cd into ChatDev again. This is because you can see that the run.py file, which needs to be executed with Python in the next step, is located in the ChatDev-main folder.
> > 
> > 
> > Could You please briefly explain this to me ?
> 
> In short, you can skip the step in your third line.

can i directly start the 4th step this right one here Set OpenAI API Key: Export your OpenAI API key as an environment variable. Replace "your_OpenAI_API_key" with your actual API key. Remember that this environment variable is session-specific, so you need to set it again if you open a new terminal session. On Unix/Linux:?

**Comment by Alphamasterliu** [comment]
> > > > Hi, according to the path you've shared, you have actually entered the ChatDev-main folder before activating the conda environment, so there's no need to cd into ChatDev again. This is because you can see that the run.py file, which needs to be executed with Python in the next step, is located in the ChatDev-main folder.
> > > 
> > > 
> > > Could You please briefly explain this to me ?
> > 
> > 
> > In short, you can skip the step in your third line.
> 
> can i directly start the 4th step this right one here Set OpenAI API Key: Export your OpenAI API key as an environment variable. Replace "your_OpenAI_API_key" with your actual API key. Remember that this environment variable is session-specific, so you need to set it again if you open a new terminal session. On Unix/Linux:?

Yes : ) Because in the previous configuration steps, you have already operated under the ChatDev folder.😊

**Comment by Kanuj7** [comment]
> > > > > Hi, according to the path you've shared, you have actually entered the ChatDev-main folder before activating the conda environment, so there's no need to cd into ChatDev again. This is because you can see that the run.py file, which needs to be executed with Python in the next step, is located in the ChatDev-main folder.
> > > > 
> > > > 
> > > > Could You please briefly explain this to me ?
> > > 
> > > 
> > > In short, you can skip the step in your third line.
> > 
> > 
> > can i directly start the 4th step this right one here Set OpenAI API Key: Export your OpenAI API key as an environment variable. Replace "your_OpenAI_API_key" with your actual API key. Remember that this environment variable is session-specific, so you need to set it again if you open a new terminal session. On Unix/Linux:?
> 
> Yes : ) Because in the previous configuration steps, you have already operated under the ChatDev folder.😊 The command `cd ChatDev` means to enter the ChatDev folder.

please help me i need your support on this 
![Uploading sytax error.PNG…]()

**Comment by NA-Wen** [comment]
It seems that you are using a command prompt (CMD) on windows system. Try to utilize PowerShell to set the environment variables. 
Or you can directly edit your environments variables in the Power User Task Menu on windows.
