### ISSUE TITLE
Add ollama integration instruction in the readme .

### ISSUE THREAD

**Issue by hemangjoshi37a** [OpenBMB/ChatDev#352]
Please anyone who has write access to this repo please provide any documentation or anything on how to replace openAI models with ollama models . thanks .

**Comment by XZH-HZX** [comment]
Hi:) You can adjust the relevant settings in the model_backend.py, including modeltype, your API_KEY, etc.

**Comment by thinh9e** [comment]
If you want to use Ollama in local setup, you can follow my steps:
1. Set environment variables:
    ```bash
    export OPENAI_API_KEY=ollama  # any value
    export BASE_URL=http://localhost:11434/v1  # your Ollama API server
    ```
2. Replace `model` parameter to your model in Ollama:
  https://github.com/OpenBMB/ChatDev/blob/bbb145048ef1a1be727cd4f176b8bafe1a5f15db/camel/model_backend.py#L100
  Example:
    ```python
    response = client.chat.completions.create(*args, **kwargs, model="gemma:2b-instruct",
                                              **self.model_config_dict)
    ```
3. Run:
    ```bash
    python3 run.py --task "[description_of_your_idea]" --name "[project_name]"
    ```

**Comment by hemangjoshi37a** [comment]
@thinh9e  ok thanks. but this should be added to the readme file so that it is accessible to anyone.

**Comment by rqi14** [comment]
> If you want to use Ollama in local setup, you can follow my steps:
> 
> 1. Set environment variables:
>    ```shell
>    export OPENAI_API_KEY=ollama  # any value
>    export BASE_URL=http://localhost:11434/v1  # your Ollama API server
>    ```
> 2. Replace `model` parameter to your model in Ollama:
>    https://github.com/OpenBMB/ChatDev/blob/bbb145048ef1a1be727cd4f176b8bafe1a5f15db/camel/model_backend.py#L100
>    
>    Example:
>    ```python
>    response = client.chat.completions.create(*args, **kwargs, model="gemma:2b-instruct",
>                                              **self.model_config_dict)
>    ```
> 3. Run:
>    ```shell
>    python3 run.py --task "[description_of_your_idea]" --name "[project_name]"
>    ```

Hi. I get the below error. it seems the model name has to be supported by tiktoken. Is there any way to bypass it so that open models can be used?
