### ISSUE TITLE
cannot further optimize the generated software result. 

### ISSUE THREAD

**Issue by karlchangretta** [OpenBMB/ChatDev#356]
It seems that ChatGPT currently cannot further optimize the generated software result. This means that if the result is unsatisfactory or flawed, it cannot request the small company to optimize the software, and it can only generate it from scratch again.

**Comment by JiahaoLi2003** [comment]
My understanding is that you want to do incremental development based on the software generated by ChatDev.
Try `--config "incremental" --path "[source_code_directory_path]"`
