### ISSUE TITLE
Issue with ModuleNotFoundError Despite Successful Package Installation

### ISSUE THREAD

**Issue by yoan34** [OpenBMB/ChatDev#359]
Hi,

I'm encountering a **ModuleNotFoundError** that I've been unable to resolve despite attempting several solutions. I've detailed the steps I've taken below and am seeking guidance on what might be causing this issue and how to fix it.

Steps I've followed:

- Installed dependencies using Poetry with my pyproject.toml. Here's a snippet of my **pyproject.toml**

```
[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["my_mail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
sqlalchemy = "^2.0.28"
tenacity = "^8.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- activated the virtual environment
- confirmed that other modules are imported without any issues
- attempted to run my fastAPI application with the following command: `poetry run uvicorn new_app.main:api --reload`
- Verified the installation of the **tenacity** package using `poetry show | grep tenacity` which confirms the package is installed
- Successfully imported the **tenacity** package in an interactive Python session initiated with:
```
poetry run python
>>>import tenacity
```

Despite these steps, when I attempt to run my application, I still face a ModuleNotFoundError for the tenacity package. All other modules are imported correctly, and this issue seems to be isolated to tenacity.

Does anyone have any suggestions on what might be causing this issue or additional steps I could take to resolve it?

**Comment by wyifei26** [comment]
Maybe these issues before can help you? #30 #155

**Comment by yoan34** [comment]
I already see the 30 and the 155 doesn't help me

**Comment by wyifei26** [comment]
Or maybe suggestions below?
- **Check `tenacity` Version Compatibility**: Sometimes, new versions of packages may not be compatible with other dependencies used in your project. It's a good idea to review the version history and changelog of `tenacity` to identify any known compatibility issues. If you're unsure, consider testing with an earlier version of `tenacity`.

-  **Check Environment Variables**: Ensure there are no incorrect environment variable or path settings that could interfere with Python's dependency lookup. Pay special attention to the `PYTHONPATH` environment variable.

-  **Rebuild the Virtual Environment**: Occasionally, recreating the virtual environment can solve elusive issues. Try deleting the current virtual environment and let Poetry recreate and reinstall all dependencies.
