### ISSUE TITLE
[BUG]Weird pixels of sign appears around agent

### ISSUE THREAD

**Issue by tunglinwood** [OpenBMB/ChatDev#362]
Hi,
I have this weird pixels of sign putting up when the language model changed to bard.
<img width="633" alt="image" src="https://github.com/OpenBMB/ChatDev/assets/113751333/4560a3af-2119-4080-9f09-e64f4fcfe9af">

**Comment by NA-Wen** [comment]
This issue seems to extend beyond our project alone. More information is preferred to effectively address this issue.

**Comment by thinkwee** [comment]
looks like you turned to the wrong project, maybe the "chatdev" you tried is this [one](https://github.com/10cl/chatdev)?(which has no relationship with our ChatDev project)
