### ISSUE TITLE
window安装完成后出现一个弹窗，输入内容点send反应

### ISSUE THREAD

**Issue by SkyDerick** [OpenBMB/ChatDev#363]
window执行最后一步python main.py后弹出一个对话框，随便输入内容点击send没反应

**Comment by NA-Wen** [comment]
Is this issue occurring while running ChatDev itself or while running the software generated by ChatDev? Providing more details will help in resolving the issue effectively.

**Comment by thinkwee** [comment]
If you have any updates on this problem, please reopen this issue and paste your log so we can help it.
