### ISSUE TITLE
Confusing Installation isntruction in replay

### ISSUE THREAD

**Issue by dlwby1985** [OpenBMB/ChatDev#366]
Hi:
   I use ChatDev to create a translation GPT using ChatGPT. In the installation instructions, it says
"Clone or download the Translation GPT repository from the ChatDev GitHub page (https://github.com/ChatDev/Translation-GPT)."
  But there is no https://github.com/ChatDev/Translation-GPT at all. Any idea where is the repository?
![image](https://github.com/OpenBMB/ChatDev/assets/149436379/295217e7-eb6b-4310-8953-e022f099aea6)

![image](https://github.com/OpenBMB/ChatDev/assets/149436379/f0349505-346d-4dda-80db-00c865421e39)

**Comment by JYM0000** [comment]
Regarding your question, "Translation-GPT" does not exist in ChatDev GitHub. The software you develop with chatdev will be stored directly on your computer (its python files will be in the WareHouse folder), and you won't need to download it.
