### ISSUE TITLE
运行 python run.py --task "[description_of_your_idea]" --name "[project_name]" 后长时间没有响应

### ISSUE THREAD

**Issue by icemen380** [OpenBMB/ChatDev#368]
我按照指南上配置的环境但是执行(ChatDev_conda_env) D:\Python_Projects\ChatDev>python run.py --task "design a basic Gomoku game" --name "Gomoku"
命令后长时间没有响应，请问这个问题是怎么回事，是和我的环境相关吗？

**Comment by icemen380** [comment]
![20240408212311](https://github.com/OpenBMB/ChatDev/assets/49834136/3e1bd856-bdd9-4b82-a51f-8410ec9f1db7)

**Comment by icemen380** [comment]
我用的windows11除了在CMD里用set设置了OPENAI_API_KEY环境变量外，在计算机属性的环境变量设置里面也设置了这个环境变量。

**Comment by JYM0000** [comment]
Regarding your question, you can check that your API is working and make sure that all the proxy tool is turned off.

**Comment by Alphamasterliu** [comment]
> ![20240408212311](https://private-user-images.githubusercontent.com/49834136/320498137-3e1bd856-bdd9-4b82-a51f-8410ec9f1db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDA3NjksIm5iZiI6MTcxMjc0MDQ2OSwicGF0aCI6Ii80OTgzNDEzNi8zMjA0OTgxMzctM2UxYmQ4NTYtYmRkOS00YjgyLWE1MWYtODQxMGVjOWYxZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NWM0NWY3YmEwZjU5N2RkNWE2Zjk2YWM3NWE4NmZiYzM5ZGQyNDg3MGI4MGZjODg0ZGI5NDdiZDQ0YzQyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hT84PhkTMl0WWY1OEGm0sKgTNGibYNj4_fl0oeOQlls)

hi，您可以看看ChatDev对应生成到WareHouse的文件夹，里面的log文件（文件末尾，一般会有可辨别的报错原因）
