### ISSUE TITLE
执行到第5步，构建您的软件。出现错误提示。

### ISSUE THREAD

**Issue by Rltcc** [OpenBMB/ChatDev#369]
tenacity.RetryError: RetryError[<Future at 0x1b0f8ed2f70 state=finished raised RateLimitError>]

这个问题需要怎么解决？

**Comment by haishuowang** [comment]
这个应该是openai api key错误导致的
比如环境配置的时候是不是把引号也加进去了之类的

**Comment by JYM0000** [comment]
You can check to see if your network is working or try again later.
