### ISSUE TITLE
使用GPT4异常

### ISSUE THREAD

**Issue by getgptpro** [OpenBMB/ChatDev#376]
使用如下命令可以正常的生成项目：
`python3 run.py --task "写一个web网站，实现注册登录功能" --name "SimpleWeb"`

但是指定模型为GPT4，会异常：
`python3 run.py --task "写一个web网站，实现注册登录功能" --name "SimpleWeb" --model "GPT_4_TURBO"`

执行一段时间后，会在打印日志 Chief Technology Officer: **[Start Chat]** 后，一直打印日志：
Retrying request to /chat/completions in xxxx seconds

**Comment by thinkwee** [comment]
我们刚刚更新了backend llm配置，请再试一下？
