### ISSUE TITLE
怎么对一个已经生成的项目进行持续改进

### ISSUE THREAD

**Issue by kangxiaolan** [OpenBMB/ChatDev#381]
我用chatdev生成了一个项目之后，发现了有很多需要改进的地方，我想在这个项目的基础上进行持续开发，但是没看懂要怎么做。

**Comment by Alphamasterliu** [comment]
Hi，您可以关注一下我们去年11月2日更新的“增量开发”功能，在终端用python运行ChatDev时，配置系统`--config "incremental" `和项目路径`--path "[source_code_directory_path]"`，希望对你有帮助：）
#November 2, 2023: ChatDev is now supported with a new feature: incremental development, which allows agents to develop upon existing codes. Try` --config "incremental" --path "[source_code_directory_path]"` to start it.
