### ISSUE TITLE
SRDD dataset interpretation

### ISSUE THREAD

**Issue by jiange91** [OpenBMB/ChatDev#386]
Hi, very impressive work. Can you provide column names in the `check.csv` file for better understanding of the results.

**Comment by thinkwee** [comment]
We have updated the file head for ``check.csv`` and we also give instruction on the readme of SRDD. 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/2f06c322-ce29-4c4d-abcb-396e30b6b239">
