### ISSUE TITLE
Official Evaluation Script

### ISSUE THREAD

**Issue by mshen2** [OpenBMB/ChatDev#388]
Thanks for the amazing work! 
I am wondering if it is possible the official evaluation code (Completeness, Executability, Consistency) can be shared?
Thanks!

**Comment by PhyllisH** [comment]
Is this issue fixed? I have the same question.

**Comment by mshen2** [comment]
Yes, authors have uploaded the script at [here](https://github.com/OpenBMB/ChatDev/blob/main/chatdev/eval_quality.py).
