### ISSUE TITLE
Where is the Experiential Co-Learning code?

### ISSUE THREAD

**Issue by ShuxianMa** [OpenBMB/ChatDev#389]
Could you tell me where the code is implemented? thank you

**Comment by NA-Wen** [comment]
The main component is implemented in [ecl](https://github.com/OpenBMB/ChatDev/tree/main/ecl), and the documentation can be found under the [experiential-co-learning-guide](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#experiential-co-learning-guide).
