### ISSUE TITLE
I wish to add a non-AI character (myself)

### ISSUE THREAD

**Issue by CrazyBunQnQ** [OpenBMB/ChatDev#398]
When a non-AI character is configured and it's that character's turn to speak, it's up to me to do the input to talk to the other agents.

Because there are many complex situations, such as specific operating environments, specific knowledge bases, etc., when steps that ordinary agents cannot complete correctly no matter what, the user can operate and provide feedback.

For example: Set the test engineer type to myself, then when it is the test engineers' turn to test the code, I can run the code they wrote in a real and available environment and feedback real error messages.

**Comment by shiowen** [comment]
Thank you for reaching out.
We've got a feature called [human-agent-interaction](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#human-agent-interaction), and you can try this out.

**Comment by CrazyBunQnQ** [comment]
> Thank you for reaching out.
> 
> We've got a feature called [human-agent-interaction](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#human-agent-interaction), and you can try this out.

Okay! Thank you very much Well done!
