### ISSUE TITLE
i an irritating issue of the installation of chatdev in the first step itself

### ISSUE THREAD

**Issue by easterbro** [OpenBMB/ChatDev#402]
Cloning into 'ChatDev'...
remote: Enumerating objects: 2738, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (240/240), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5930 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by ChosenFewPet** [comment]
Nice work I just finished looking for something like this please feel free to contact me

**Comment by Linuxscot1974** [comment]
hi,
This is a slow network connection error.  I wrote a small app ( with ChatGPT ) that allows me to re-establish a new connection and then recursively look for the last folder/file and start the request process from their.  Its not perfect but it works as a semi-type download manager and I was able to clone the whole folder after 4 attempts at re-connection.  
I wish githubs own GUI manager had the facility for this.
Good luck !

**Comment by easterbro** [comment]
thanks man i am having problems , since i am and rookie at these things i don't know thing about coding so it kind of confusing to follow thru and i encounter constant problems while installation

**Comment by easterbro** [comment]
\Users\meetm>conda create -n ChatDev_conda_env python=3.9 -y
'conda' is not recognized as an internal or external command,
operable program or batch file. [ another problem , i have conda installed btw ]

**Comment by shiowen** [comment]
Hi, the error message "'conda' is not recognized as an internal or external command, operable program or batch file" typically indicates that the conda executable is not found in your system's PATH environment variable.
You can try add Conda to PATH.
