### ISSUE TITLE
AI Agent to understand ChatDev better!

### ISSUE THREAD

**Issue by samyakkkk** [OpenBMB/ChatDev#412]
Dear maintainers, Greetings from [CommandDash](https://commanddash.io)!

We're an AI tool that helps developers understand and build with open-source repositories.

There has been request to create an agent for this repository and it is ready to [try here!](https://app.commanddash.io/agent?github=https://github.com/OpenBMB/ChatDev).

**_Demo of an agent in action:_**

https://github.com/user-attachments/assets/58588c4a-4dad-4219-9731-862dec99a00a

- Allows searching for files and issues.
- Ask questions to better understand the repository.
- Get assistance using it within their project.

If this could be of help to other developers, you can mention it as a badge in your readme. Or, please close this issues if not.

<a href="https://app.commanddash.io/agent?github=https://github.com/OpenBMB/ChatDev"><img src="https://img.shields.io/badge/AI-Code%20Gen-EB9FDA"></a>
```
<a href="https://app.commanddash.io/agent?github=https://github.com/OpenBMB/ChatDev"><img src="https://img.shields.io/badge/AI-Code%20Gen-EB9FDA"></a>
```

Many thanks.

**Comment by zhanghb18** [comment]
Thank you for providing this tool! We will evaluate whether it is helpful to other developers.
