### ISSUE TITLE
代码版本和论文对应关系

### ISSUE THREAD

**Issue by JinFish** [OpenBMB/ChatDev#463]
在最新版本的README中你们提到“2024年1月25日: 已在 ChatDev 中更新了 "Experiential Co-Learning" 模块”，让我担心这在原论文的基础上增加了额外的功能，而我我只想通过“ChatDev: Communicative Agents for Software Development”这篇论文来学习如何使用多智能体来完成一个任务。

因此，我的疑问是：目前最新仓库的代码是否是“ChatDev: Communicative Agents for Software Development”的对应，还是说在此基础上添加了额外的功能。如果我想要“ChatDev: Communicative Agents for Software Development”对应的代码，我应该使用哪个版本的仓库代码。

非常感谢你们的工作，期待你们的回复！！！

**Comment by NA-Wen** [comment]
**You can directly use the current version of the code.** The "Experiential Co-Learning" module is disabled by default and can be controlled using the `with_memory` hyperparameter, as described in the [ChatChain configuration guide](https://github.com/OpenBMB/ChatDev/blob/main/wiki.md#chatchain-parameters).

**Comment by JinFish** [comment]
Thnk you.
