### ISSUE TITLE
when agents use flask they do not create templates folder inside project folder

### ISSUE THREAD

**Issue by sojohnnysaid** [OpenBMB/ChatDev#48]
Several times the agents will be working on a flask app and the index.html etc will be created within the project folder, instead of the agent creating a template folder, then the index.html inside. Any way to work around this. I would like to avoid manually fixing this every time. Thank you for this repo, it's really great work.

**Comment by lijiahao2022** [comment]
Thank you for your feedback.
It does not support the ability to automatically create complex directory structures currently, and this feature will be supported in the future, so please stay tuned .
