### ISSUE TITLE
How do you stop it once it's running? 

### ISSUE THREAD

**Issue by NeVeREire** [OpenBMB/ChatDev#52]
If it's starts before you are ready, how do you stop it?

**Comment by lijiahao2022** [comment]
Thank you for your feedback. 
Don't worry, this is an automatic testing process for ChatDev that will only last 5 seconds and then automatically close,just ignore that.The formal program requires the user to start it manually.

**Comment by NeVeREire** [comment]
Yes I know, 

When I mean is, I was entering my task, and pressed Enter, and it started, But I didn't mean to press enter, so it ran for long time with an incomplete task

**Comment by lijiahao2022** [comment]
I understand that you are having problems at this step：
`python3 run.py --task "[description_of_your_idea]" --name "[project_name]"`
You can exit the currently running process directly through `Ctrl+C` at the terminal,and the corresponding process will be killed by the operating system.
If you encounter other problems, feel free to continue submitting issues.
