### ISSUE TITLE
RetryError[<Future at 0x161c7ae02b0 state=finished raised ValueError>]

### ISSUE THREAD

**Issue by zack-rgb** [OpenBMB/ChatDev#56]
这是咋回事，我在win10 中跑代码出现这个问题解决一下

**Comment by lijiahao2022** [comment]
使用以下命令设置OpenAI API密钥：
`$env:OPENAI_API_KEY="your_OpenAI_API_key"`

注意将"your_OpenAI_API_key" 替换为您的实际API密钥
