### ISSUE TITLE
These parameters can be replaced 

### ISSUE THREAD

**Issue by xjspace** [OpenBMB/ChatDev#6]
#openAI
OPENAI_BASE_URL
OPENAI_API_KEY
example
#cladue2
cladue2_BASE_URL
cladue2_API_KEY

These parameters can be replaced with a configuration file, preferably with other APIs to increase their flexibility

**Comment by ashish2508** [comment]
# Configuration for OpenAI API
openai:
  base_url: OPENAI_BASE_URL
  api_key: OPENAI_API_KEY

# Configuration for Example API
example:
  base_url: EXAMPLE_BASE_URL
  api_key: EXAMPLE_API_KEY

# Configuration for Claude2 API
claude2:
  base_url: CLAUDE2_BASE_URL
  api_key: CLAUDE2_API_KEY

**Comment by thinkwee** [comment]
Thank you. We have noticed that the community wants a [general endpoint for either local-host LLM or other online API](https://github.com/OpenBMB/ChatDev/pull/4). We would consider making a update about it in the near future.
