### ISSUE TITLE
Failed to send message.

### ISSUE THREAD

**Issue by laovvvcom** [OpenBMB/ChatDev#65]
本地可以正常起服务，运行run.py也没问题，就是python3 run.py --task "XXX" --name "XXX"的时候，报Failed to send message.
可以点拨下可能出现的原因吗

**Comment by NA-Wen** [comment]
Could you please provide more detailed error message ?

**Comment by laovvvcom** [comment]
| **user_role_name** | Chief Technology Officer |
| **assistant_role_prompt** | {chatdev_prompt} You are Programmer. we are both working at ChatDev. We share a common interest in collaborating to successfully complete a task assigned by a new customer. You can write/create computer software or applications by providing a specific programming language to the computer. You have extensive computing and coding experience in many varieties of programming languages and platforms, such as Python, Java, C, C++, HTML, CSS, JavaScript, XML, SQL, PHP, etc,. Here is a new customer's task: {task}. To complete the task, you must write a response that appropriately solves the requested instruction based on your expertise and customer's needs. |
| **user_role_prompt** | {chatdev_prompt} You are Chief Technology Officer. we are both working at ChatDev. We share a common interest in collaborating to successfully complete a task assigned by a new customer. You are very familiar to information technology. You will make high-level decisions for the overarching technology infrastructure that closely align with the organization's goals, while you work alongside the organization's information technology ("IT") staff members to perform everyday operations. Here is a new customer's task: {task}. To complete the task, You must write a response that appropriately solves the requested instruction based on your expertise and customer's needs. |
| **task_prompt** | 制作折线图表 |
| **with_task_specify** | False |
| **model_type** | ModelType.GPT_3_5_TURBO |

Failed to send message.
Chief Technology Officer: **[Start Chat]**

**Comment by NA-Wen** [comment]
According to the messgae you provided,  `"Failed to send message."` seems to appear in log file. It means you did not start the local demo(flask app), which includes enhanced visualized logs, replay demo, and a simple ChatChain Visualizer.
By using 
`python3 online_log/app.py`
you can start the flask app.
More details about the usage of this local demo are shown in our wiki.

**Comment by NA-Wen** [comment]
According to the messgae you provided, "Failed to send message." seems to appear in log file. It means the local demo(flask app) was not started correctly. The specific HTTP request (to local port 8000) has not been successfully completed (with https response status code != 200 ).

You can try to restart the flask app before running  'run.py' by using 
`python3 online_log/app.py`
More details about the usage of this local demo are shown in our wiki.
