### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by AndryHTC** [OpenBMB/ChatDev#70]
Hi!
Amazing project. I was wondering if it's planned to support more languages other than Python

**Comment by yashkite** [comment]
yes I was also looking for the same

**Comment by AndryHTC** [comment]
> Do you mean programing languages or other LLM models like code LLaMa, phi 1.5 etc

Programming languages, other than Python, that seems the only one supported

**Comment by NA-Wen** [comment]
Thank you for your suggestions !
In current version , the `programmer` prefers python when choosing a programming language , and in some cases , html/javascript is also used(like [Website_THUNLP_20230725154612](https://github.com/OpenBMB/ChatDev/tree/main/WareHouse/Website_THUNLP_20230725154612)). We will give your suggestion our careful consideration for further development.
