### ISSUE TITLE
 The originally correct code turned into incorrect code due to the misleading guidance from the Code Reviewer.

### ISSUE THREAD

**Issue by yunyunyun23** [OpenBMB/ChatDev#72]
task_prompt: a simple gomoku game

For detailed information, please refer to the log files. The last version of the code before the involvement of the Code Reviewer was functional. However, after the Code Reviewer's involvement, erroneous suggestions were made, leading to multiple rounds of meaningless error discussions. Ultimately, this resulted in the correct code being modified into incorrect code.
[gomoku_DefaultOrganization_20230919130000.log](https://github.com/OpenBMB/ChatDev/files/12664832/gomoku_DefaultOrganization_20230919130000.log)

**Comment by NA-Wen** [comment]
Thank you for your feedback !
Due to the hallucinations emerging in LLM, there might be some erroneous suggestions provided by `code reviewer`. We will develop further to improve this part.
