### ISSUE TITLE
It seems that ChatDev can only build python software.

### ISSUE THREAD

**Issue by staradventure** [OpenBMB/ChatDev#74]
![image](https://github.com/OpenBMB/ChatDev/assets/91239079/928c2a2a-0cff-4181-8a96-afe5ddae7916)
[GreenLife_DefaultOrganization_20230920150110.log](https://github.com/OpenBMB/ChatDev/files/12670318/GreenLife_DefaultOrganization_20230920150110.log)
I've tried making an uni-app,but it cannot generate correct files for uni-app.

**Comment by NA-Wen** [comment]
Please refer to [issues #70 ](https://github.com/OpenBMB/ChatDev/issues/70)
