### ISSUE TITLE
Is it possible to replay with edits?

### ISSUE THREAD

**Issue by zethereumGmail** [OpenBMB/ChatDev#8]
The finished product was ok, but I want to rerun the project without it having to do all the work again but inject a simple instruction that would make the finished product better.

I asked it to create a gui chess board and run the knights journey from a starting position I pick by clicking with my mouse button. It basically created this, but when I ran it and selected the starting position it froze. I want to send the product back through the assembly line with a minor change. Is this possible?

**Comment by thinkwee** [comment]
Thank you for your feedback! Yes, we often do not need to create the software from scratch but make changes to the already-built software. We are considering three ways to achieve such a goal:

1. We roll back some steps in the ChatChain and restart from a certain step, just like what you proposed.
2. Define a new ChatChain, that only reads existing software files and makes the review and test steps to improve the software.
3. Include a new ``Phase`` called ``CodeReviewHuman`` in the ChatChain. This phase has been realized but we haven't put it in the default ChatChain. It allows you to have multiple rounds of conversations with the agent, give the user's own reviews, propose new requirements, and update the code.

We haven't decided yet that which one is the best solution to this problem, but it has been taken into considertaion in our roadmap.

**Comment by zethereumGmail** [comment]
Thank you, you are creating something awesome. Please keep it going.
