### ISSUE TITLE
ChatDev can't update code of existing 'WareHouse' Projects

### ISSUE THREAD

**Issue by mariusorani** [OpenBMB/ChatDev#80]

**Comment by BishAU** [comment]
correct and not many work one shot either, hand em over to AutoGPT to fix them up or mentat or aider

**Comment by mariusorani** [comment]
While handing the project over to aider & co seem to be a good Idea, i thought maybe will ChatDev implement it's own logic on updating the codebase of it's own projects at user prompt. I think this could be a major feature

**Comment by BishAU** [comment]
I would agree and they have hinted at it. There can only be so many snake games :) I will look next at the agents and might craft myself a nasty head dev modelled on my own boss. actually no, he is a cunt.

**Comment by Alamdar04** [comment]
The feature is necessary if we are to really run a profitable software company with this.

**Comment by mariusorani** [comment]
addapting the Aider's functionality into ChatDev will do the thing maybe ;)

**Comment by giorgosn** [comment]
What would be needed to achive a functionality like this?

**Comment by realjuangalt** [comment]
> What would be needed to achive a functionality like this?

It probably needs the human interaction feature to be more developed. I just tested it and It didn't really work. But that's clearly the direction they want to take it. Basically the program should run until the user asks it to shut down and should wait for user feedback on the product after a certain cycle.

**Comment by robertluisw** [comment]
The closest they have to this capability is their "human interaction" feature, which allows the user to act as a reviewer and add a one line alteration request upon review.  After submission of the change request, ChatDev will loop back into the development process. There is a max of 5 iterations allowed.  I agree though, it would be very handy if a more capability was provided for allowing editing. I've created three apps so far, and all of them have required a very large amount of modifications. Any requirement that wasn't explicitly clarified in the design idea prompt is hallucinated to allow the process to continue and for the agents to complete the objective.  It would be great if the agent team asked clarifying questions during the design process. A one line prompt is simply not sufficient.

**Comment by Luzzotica** [comment]
I agree with all of the above. Being able to interact with the project directly as it's being developed would be super nice.
Or even to come in after a couple of iterations and provide feedback, have the AI generate a list of questions to ask the user that it presents to us after the iterations.

**Comment by Monotoba** [comment]
I am working on an IDE concept that incorporates AI agents as part of the software development experience. Sage IDE , will incorporate AI agents that work interactively with the software developer to produce a project from start to finish.  The project is open to comments, suggestions, and questions: https://github.com/Monotoba/SageIDE/
